// Archivo generado desde Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx
// No editar manualmente si se vuelve a importar el Excel fuente.
export const importedInmueblesVersion = "v43-2026-08-05";
export const importedPropertyOwners = [
  {
    "id": "PROP-LFHV",
    "name": "Luis Felipe Herrera Vázquez",
    "personType": "Pendiente definir",
    "rfc": "",
    "email": "",
    "phone": "",
    "status": "Activo",
    "notes": "Propietario inferido por relación de inmuebles; confirmar datos fiscales."
  }
];
export const importedDepositAccounts = [
  {
    "id": "ACC-LFHV-PENDIENTE",
    "ownerId": "PROP-LFHV",
    "alias": "Pendiente asignar",
    "bank": "",
    "beneficiary": "Luis Felipe Herrera Vázquez",
    "account": "",
    "clabe": "",
    "currency": "MXN",
    "status": "Pendiente",
    "use": "Rentas / depósitos",
    "notes": "Un propietario puede tener más de una cuenta; seleccionar cuenta específica en inmueble o contrato."
  }
];
export const importedInmuebles = [
  {
    "id": "INM-001-estacionamiento-itzimna-mario-correa",
    "name": "ESTACIONAMIENTO ITZIMNA - MARIO CORREA",
    "projectId": "",
    "type": "Local comercial",
    "area": 1730.55,
    "location": "CALLE 21 #106 X 22 Y 24 ITZIMNA",
    "address": "CALLE 21 #106 X 22 Y 24 ITZIMNA",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 1268.92433,
    "coordinates": "20.9914866210934,-89.6136481257926",
    "latitude": 20.9914866210934,
    "longitude": -89.6136481257926,
    "mapsUrl": "https://www.google.com/maps/place/20%C2%B059'29.2%22N+89%C2%B036'49.3%22W/@20.9914647,-89.6139213,133m/data=!3m1!1e3!4m5!3m4!4b1!8m2!3d20.9914562!4d-89.6136844?hl=es&entry=ttu&g_ep=EgoyMDI1MTEwOS4wIKXMDSoASAFQAw%3D%3D",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 2195937,
    "cadastralValueM2": 1268.92433,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 555",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 3",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-002-oficina-eladios",
    "name": "OFICINA ELADIOS",
    "projectId": "",
    "type": "Local comercial",
    "area": 1080,
    "location": "CALLE 12-A #333 X 20 Y 35 DIAG PEDREGALES DE TANLUM",
    "address": "CALLE 12-A #333 X 20 Y 35 DIAG PEDREGALES DE TANLUM",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 1225,
    "coordinates": "21.0010371190667,-89.6283138386853",
    "latitude": 21.0010371190667,
    "longitude": -89.6283138386853,
    "mapsUrl": "https://maps.app.goo.gl/oznaSAShVc1mz2m67",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 1323000,
    "cadastralValueM2": 1225,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 289",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 4",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-003-estacionamiento-pensiones",
    "name": "ESTACIONAMIENTO PENSIONES",
    "projectId": "",
    "type": "Local comercial",
    "area": 638.12,
    "location": "CALLE 28 #224 X 7 Y 9 GARCIA GINERES",
    "address": "CALLE 28 #224 X 7 Y 9 GARCIA GINERES",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 1783.306996,
    "coordinates": "20.9943462500483,-89.6352576774925",
    "latitude": 20.9943462500483,
    "longitude": -89.6352576774925,
    "mapsUrl": "https://maps.app.goo.gl/MoqPfZQXKCFsUru17",
    "status": "Disponible",
    "commercialStatus": "EN RENTA",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 1137963.86,
    "cadastralValueM2": 1783.306996,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 141",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 5",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-004-lote-de-autos-calle-60-automaya",
    "name": "LOTE DE AUTOS CALLE 60-AUTOMAYA",
    "projectId": "",
    "type": "Local comercial",
    "area": 1186.94,
    "location": "CALLE 60 #262 MEXICO",
    "address": "CALLE 60 #262 MEXICO",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 4305.002528,
    "coordinates": "21.0039620269139,-89.6223182961375",
    "latitude": 21.0039620269139,
    "longitude": -89.6223182961375,
    "mapsUrl": "https://maps.app.goo.gl/WH9LkQSWCzu7RYMb6",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 5109779.7,
    "cadastralValueM2": 4305.002528,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 391",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 6",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-005-restaurante-oriente-dahe",
    "name": "RESTAURANTE ORIENTE- DAHE",
    "projectId": "",
    "type": "Local comercial",
    "area": 350,
    "location": "CALLE 4 #119 - A CHUMINOPOLIS",
    "address": "CALLE 4 #119 - A CHUMINOPOLIS",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 2380,
    "coordinates": "20.9738882034552,-89.5911913413432",
    "latitude": 20.9738882034552,
    "longitude": -89.5911913413432,
    "mapsUrl": "https://maps.app.goo.gl/KdBPkK31j4N7SyYX9",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 833000,
    "cadastralValueM2": 2380,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 722",
    "hasCadastralCertificate": "SI",
    "hasPlan": "NO HAY PLANOS",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 7",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-006-lote-de-autos-fco-montejo",
    "name": "LOTE DE AUTOS FCO MONTEJO",
    "projectId": "",
    "type": "Local comercial",
    "area": 1672.5,
    "location": "CALLE 24-A #300  BUGAMBILIAS",
    "address": "CALLE 24-A #300  BUGAMBILIAS",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 1790,
    "coordinates": "21.0301862148465,-89.6362263795022",
    "latitude": 21.0301862148465,
    "longitude": -89.6362263795022,
    "mapsUrl": "https://maps.app.goo.gl/eu7zgdTVifR91Lk86",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 2993775,
    "cadastralValueM2": 1790,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 3898-UNION",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 8",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-007-local-plaza-fiesta",
    "name": "LOCAL PLAZA FIESTA",
    "projectId": "",
    "type": "Local comercial",
    "area": 83,
    "location": "CALLE 3 #397 X4 Y 6 GUSTAVO DIAZ ORDAZ",
    "address": "CALLE 3 #397 X4 Y 6 GUSTAVO DIAZ ORDAZ",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 1600,
    "coordinates": "20.9992455036142,-89.5973985836197",
    "latitude": 20.9992455036142,
    "longitude": -89.5973985836197,
    "mapsUrl": "https://maps.app.goo.gl/geHDjczRq9QdReXr8",
    "status": "Disponible",
    "commercialStatus": "EN RENTA",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 132800,
    "cadastralValueM2": 1600,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 288",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 9",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-008-eladios-centro-dahe",
    "name": "ELADIOS CENTRO- DAHE",
    "projectId": "",
    "type": "Local comercial",
    "area": 289,
    "location": "CALLE 59 #425 CENTRO",
    "address": "CALLE 59 #425 CENTRO",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 945,
    "coordinates": "20.9672428552061,-89.6124378953317",
    "latitude": 20.9672428552061,
    "longitude": -89.6124378953317,
    "mapsUrl": "https://maps.app.goo.gl/ed46gis1yvvkZAjv9",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 273105,
    "cadastralValueM2": 945,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 321",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 10",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-009-llantera-san-antonio-cucul-radial-llantas",
    "name": "LLANTERA SAN ANTONIO CUCUL- RADIAL LLANTAS",
    "projectId": "",
    "type": "Local comercial",
    "area": 585,
    "location": "CALLE 49 #485-C X 22 SAN ANTONIO CUCUL",
    "address": "CALLE 49 #485-C X 22 SAN ANTONIO CUCUL",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 7157.249402,
    "coordinates": "21.0212050556813,-89.6002817535398",
    "latitude": 21.0212050556813,
    "longitude": -89.6002817535398,
    "mapsUrl": "https://maps.app.goo.gl/TSif5vUvyUzLg8UPA",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 4186990.9,
    "cadastralValueM2": 7157.249402,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 439",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 11",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-010-estacionamiendo-itzaes",
    "name": "ESTACIONAMIENDO ITZAES",
    "projectId": "",
    "type": "Pendiente definir",
    "area": 171.42,
    "location": "CALLE 86-B #604- A COL CENTRO",
    "address": "CALLE 86-B #604- A COL CENTRO",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 16532.53092,
    "coordinates": "20.951566566071,-89.6457924880494",
    "latitude": 20.951566566071,
    "longitude": -89.6457924880494,
    "mapsUrl": "https://maps.app.goo.gl/xy9qUARGnSVnKdWH8",
    "status": "Revisión pendiente",
    "commercialStatus": "PENDIENTE",
    "legalStatus": "Revisar antes de cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 2834006.45,
    "cadastralValueM2": 16532.53092,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 272",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Revisar antes de cargar",
    "requiresReview": true,
    "reviewNotes": "Falta tipo; Falta estatus",
    "notes": "Origen Excel fila 12",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-011-estacionamiento-centro-dahe",
    "name": "ESTACIONAMIENTO CENTRO- DAHE",
    "projectId": "",
    "type": "Local comercial",
    "area": 642.9,
    "location": "CALLE 47 #489 X 54 Y 56 CENTRO",
    "address": "CALLE 47 #489 X 54 Y 56 CENTRO",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 2496.518277,
    "coordinates": "20.9752266642278,-89.6187267944594",
    "latitude": 20.9752266642278,
    "longitude": -89.6187267944594,
    "mapsUrl": "https://maps.app.goo.gl/hUT1eEdy84Skgq168",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 1605011.6,
    "cadastralValueM2": 2496.518277,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 48",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 13",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-012-local-1-plaza-las-vias",
    "name": "LOCAL 1 PLAZA LAS VIAS",
    "projectId": "",
    "type": "LOCAL PLAZA VIAS",
    "area": 668.99,
    "location": "CALLE 10 #364 AMPLIACION PLAN DE AYALA",
    "address": "CALLE 10 #364 AMPLIACION PLAN DE AYALA",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 13245.28319,
    "coordinates": "21.017976594678,-89.6244762924288",
    "latitude": 21.017976594678,
    "longitude": -89.6244762924288,
    "mapsUrl": "https://maps.app.goo.gl/u4kNwirEAo7qqUj39",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 8860962,
    "cadastralValueM2": 13245.28319,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 221",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 14",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-013-local-2-plaza-las-vias",
    "name": "LOCAL 2 PLAZA LAS VIAS",
    "projectId": "",
    "type": "LOCAL PLAZA VIAS",
    "area": 668.99,
    "location": "CALLE 10 #364 AMPLIACION PLAN DE AYALA",
    "address": "CALLE 10 #364 AMPLIACION PLAN DE AYALA",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 13245.28319,
    "coordinates": "21.017976594678,-89.6244762924288",
    "latitude": 21.017976594678,
    "longitude": -89.6244762924288,
    "mapsUrl": "https://maps.app.goo.gl/u4kNwirEAo7qqUj39",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 8860962,
    "cadastralValueM2": 13245.28319,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 221",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 15",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-014-local-3-plaza-las-vias",
    "name": "LOCAL 3 PLAZA LAS VIAS",
    "projectId": "",
    "type": "LOCAL PLAZA VIAS",
    "area": 668.99,
    "location": "CALLE 10 #364 AMPLIACION PLAN DE AYALA",
    "address": "CALLE 10 #364 AMPLIACION PLAN DE AYALA",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 13245.28319,
    "coordinates": "21.017976594678,-89.6244762924288",
    "latitude": 21.017976594678,
    "longitude": -89.6244762924288,
    "mapsUrl": "https://maps.app.goo.gl/u4kNwirEAo7qqUj39",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 8860962,
    "cadastralValueM2": 13245.28319,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 221",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 16",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-015-local-4-plaza-las-vias",
    "name": "LOCAL 4 PLAZA LAS VIAS",
    "projectId": "",
    "type": "LOCAL PLAZA VIAS",
    "area": 668.99,
    "location": "CALLE 10 #364 AMPLIACION PLAN DE AYALA",
    "address": "CALLE 10 #364 AMPLIACION PLAN DE AYALA",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 13245.28319,
    "coordinates": "21.017976594678,-89.6244762924288",
    "latitude": 21.017976594678,
    "longitude": -89.6244762924288,
    "mapsUrl": "https://maps.app.goo.gl/u4kNwirEAo7qqUj39",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 8860962,
    "cadastralValueM2": 13245.28319,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 221",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 17",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-016-local-5-plaza-las-vias",
    "name": "LOCAL 5 PLAZA LAS VIAS",
    "projectId": "",
    "type": "LOCAL PLAZA VIAS",
    "area": 1724.43,
    "location": "CALLE 10 #366 AMPLIACION PLAN DE AYALA",
    "address": "CALLE 10 #366 AMPLIACION PLAN DE AYALA",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 6540.338373,
    "coordinates": "21.0182437559818,-89.6246310068116",
    "latitude": 21.0182437559818,
    "longitude": -89.6246310068116,
    "mapsUrl": "https://maps.app.goo.gl/u4kNwirEAo7qqUj39",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 11278355.7,
    "cadastralValueM2": 6540.338373,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 221",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 18",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-017-local-6-plaza-las-vias",
    "name": "LOCAL 6 PLAZA LAS VIAS",
    "projectId": "",
    "type": "LOCAL PLAZA VIAS",
    "area": 1724.43,
    "location": "CALLE 10 #366 AMPLIACION PLAN DE AYALA",
    "address": "CALLE 10 #366 AMPLIACION PLAN DE AYALA",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 6540.338373,
    "coordinates": "21.0182437559818,-89.6246310068116",
    "latitude": 21.0182437559818,
    "longitude": -89.6246310068116,
    "mapsUrl": "https://maps.app.goo.gl/u4kNwirEAo7qqUj39",
    "status": "Disponible",
    "commercialStatus": "EN RENTA",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 11278355.7,
    "cadastralValueM2": 6540.338373,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 221",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 19",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-018-local-7-plaza-las-vias",
    "name": "LOCAL 7 PLAZA LAS VIAS",
    "projectId": "",
    "type": "LOCAL PLAZA VIAS",
    "area": 1724.43,
    "location": "CALLE 10 #366 AMPLIACION PLAN DE AYALA",
    "address": "CALLE 10 #366 AMPLIACION PLAN DE AYALA",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 6540.338373,
    "coordinates": "21.0182437559818,-89.6246310068116",
    "latitude": 21.0182437559818,
    "longitude": -89.6246310068116,
    "mapsUrl": "https://maps.app.goo.gl/u4kNwirEAo7qqUj39",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 11278355.7,
    "cadastralValueM2": 6540.338373,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 221",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 20",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-019-local-8-plaza-las-vias",
    "name": "LOCAL 8 PLAZA LAS VIAS",
    "projectId": "",
    "type": "LOCAL PLAZA VIAS",
    "area": 1724.43,
    "location": "CALLE 10 #366 AMPLIACION PLAN DE AYALA",
    "address": "CALLE 10 #366 AMPLIACION PLAN DE AYALA",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 6540.338373,
    "coordinates": "21.0182437559818,-89.6246310068116",
    "latitude": 21.0182437559818,
    "longitude": -89.6246310068116,
    "mapsUrl": "https://maps.app.goo.gl/u4kNwirEAo7qqUj39",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 11278355.7,
    "cadastralValueM2": 6540.338373,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 221",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 21",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-020-local-9-plaza-las-vias",
    "name": "LOCAL 9 PLAZA LAS VIAS",
    "projectId": "",
    "type": "LOCAL PLAZA VIAS",
    "area": 1012.75,
    "location": "CALLE 10 #370 AMPLIACION PLAN DE AYALA",
    "address": "CALLE 10 #370 AMPLIACION PLAN DE AYALA",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 6953.760207,
    "coordinates": "21.017976594678,-89.6244762924288",
    "latitude": 21.017976594678,
    "longitude": -89.6244762924288,
    "mapsUrl": "https://maps.app.goo.gl/u4kNwirEAo7qqUj39",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 7042420.65,
    "cadastralValueM2": 6953.760207,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 221",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 22",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-021-local-10-plaza-las-vias",
    "name": "LOCAL 10 PLAZA LAS VIAS",
    "projectId": "",
    "type": "LOCAL PLAZA VIAS",
    "area": 1012.75,
    "location": "CALLE 10 #370 AMPLIACION PLAN DE AYALA",
    "address": "CALLE 10 #370 AMPLIACION PLAN DE AYALA",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 6953.760207,
    "coordinates": "21.017976594678,-89.6244762924288",
    "latitude": 21.017976594678,
    "longitude": -89.6244762924288,
    "mapsUrl": "https://maps.app.goo.gl/u4kNwirEAo7qqUj39",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 7042420.65,
    "cadastralValueM2": 6953.760207,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 221",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 23",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-022-local-11-plaza-las-vias",
    "name": "LOCAL 11 PLAZA LAS VIAS",
    "projectId": "",
    "type": "LOCAL PLAZA VIAS",
    "area": 1012.75,
    "location": "CALLE 10 #370 AMPLIACION PLAN DE AYALA",
    "address": "CALLE 10 #370 AMPLIACION PLAN DE AYALA",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 6953.760207,
    "coordinates": "21.017976594678,-89.6244762924288",
    "latitude": 21.017976594678,
    "longitude": -89.6244762924288,
    "mapsUrl": "https://maps.app.goo.gl/u4kNwirEAo7qqUj39",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 7042420.65,
    "cadastralValueM2": 6953.760207,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 221",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 24",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-023-local-12-plaza-las-vias",
    "name": "LOCAL 12 PLAZA LAS VIAS",
    "projectId": "",
    "type": "LOCAL PLAZA VIAS",
    "area": 452.93,
    "location": "CALLE 10 #368 AMPLIACION PLAN DE AYALA",
    "address": "CALLE 10 #368 AMPLIACION PLAN DE AYALA",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 8958.192546,
    "coordinates": "21.018113708791,-89.6246874964384",
    "latitude": 21.018113708791,
    "longitude": -89.6246874964384,
    "mapsUrl": "https://maps.app.goo.gl/u4kNwirEAo7qqUj39",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 4057434.15,
    "cadastralValueM2": 8958.192546,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 221",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 25",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-024-local-13-plaza-las-vias",
    "name": "LOCAL 13 PLAZA LAS VIAS",
    "projectId": "",
    "type": "LOCAL PLAZA VIAS",
    "area": 452.93,
    "location": "CALLE 10 #368 AMPLIACION PLAN DE AYALA",
    "address": "CALLE 10 #368 AMPLIACION PLAN DE AYALA",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 8958.192546,
    "coordinates": "21.018113708791,-89.6246874964384",
    "latitude": 21.018113708791,
    "longitude": -89.6246874964384,
    "mapsUrl": "https://maps.app.goo.gl/u4kNwirEAo7qqUj39",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 4057434.15,
    "cadastralValueM2": 8958.192546,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 221",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 26",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-025-local-14-plaza-las-vias",
    "name": "LOCAL 14 PLAZA LAS VIAS",
    "projectId": "",
    "type": "LOCAL PLAZA VIAS",
    "area": 452.93,
    "location": "CALLE 9 #385 AMPLIACION PLAN DE AYALA",
    "address": "CALLE 9 #385 AMPLIACION PLAN DE AYALA",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 8958.192546,
    "coordinates": "21.0179512202582,-89.624423989353",
    "latitude": 21.0179512202582,
    "longitude": -89.624423989353,
    "mapsUrl": "https://maps.app.goo.gl/u4kNwirEAo7qqUj39",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 4057434.15,
    "cadastralValueM2": 8958.192546,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 221",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 27",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-026-local-farmacia-av-canek",
    "name": "LOCAL FARMACIA AV CANEK",
    "projectId": "",
    "type": "Local comercial",
    "area": 1770,
    "location": "CALLE 59 -A  #529 -A  PASEO DE LAS FUENTES",
    "address": "CALLE 59 -A  #529 -A  PASEO DE LAS FUENTES",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 4900.619068,
    "coordinates": "20.9798085198877,-89.6469897764194",
    "latitude": 20.9798085198877,
    "longitude": -89.6469897764194,
    "mapsUrl": "https://maps.app.goo.gl/Ns6FqVQuVE3sg24c7",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 8674095.75,
    "cadastralValueM2": 4900.619068,
    "commercialValueEstimate": 10000,
    "purchaseDeed": "ACTA 50",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 28",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-027-terreno-magnolias-loresa",
    "name": "TERRENO MAGNOLIAS- LORESA",
    "projectId": "",
    "type": "Local comercial",
    "area": 1995.63,
    "location": "#318 C. 60 FRACC LA MAGNOLIAS",
    "address": "#318 C. 60 FRACC LA MAGNOLIAS",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 2565,
    "coordinates": "21.0198887179036,-89.6599083369828",
    "latitude": 21.0198887179036,
    "longitude": -89.6599083369828,
    "mapsUrl": "https://maps.app.goo.gl/JNfjgwUXHikaQCtG9",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 5118790.95,
    "cadastralValueM2": 2565,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 778",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": 2025,
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 29",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-028-local-farmacia-macroplaza-div1",
    "name": "LOCAL FARMACIA MACROPLAZA DIV1",
    "projectId": "",
    "type": "Local comercial",
    "area": 1605.35,
    "location": "CALLE 33 DIAGONAL  # 226 FRACC POLIGONO ITZIMNA DIVISION 1",
    "address": "CALLE 33 DIAGONAL  # 226 FRACC POLIGONO ITZIMNA DIVISION 1",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 2254.09938,
    "coordinates": "20.9998276682892,-89.5719527660625",
    "latitude": 20.9998276682892,
    "longitude": -89.5719527660625,
    "mapsUrl": "https://maps.app.goo.gl/wGhgUdRpVEhg7hTg8",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 3618618.44,
    "cadastralValueM2": 2254.09938,
    "commercialValueEstimate": 25000,
    "purchaseDeed": "ACTA 501",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 30",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-029-local-farmacia-macroplaza-div2",
    "name": "LOCAL FARMACIA MACROPLAZA DIV2",
    "projectId": "",
    "type": "Terreno",
    "area": 567.7,
    "location": "CALLE 33 DIAGONAL #224-A FRACC POLIGONO ITZIMNA  DIVISION 2",
    "address": "CALLE 33 DIAGONAL #224-A FRACC POLIGONO ITZIMNA  DIVISION 2",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 2645.646468,
    "coordinates": "21.0000303378722,-89.5720110092933",
    "latitude": 21.0000303378722,
    "longitude": -89.5720110092933,
    "mapsUrl": "https://maps.app.goo.gl/wGhgUdRpVEhg7hTg8",
    "status": "Disponible",
    "commercialStatus": "EN RENTA",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 1501933.5,
    "cadastralValueM2": 2645.646468,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 665",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 31",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-030-local-1",
    "name": "LOCAL 1",
    "projectId": "",
    "type": "LOCAL PLAZA FARO",
    "area": 425,
    "location": "#650 CALLE 31 FRACCIONAMIENTO CIUDAD CAUCEL",
    "address": "#650 CALLE 31 FRACCIONAMIENTO CIUDAD CAUCEL",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 18879.94461,
    "coordinates": "21.0052077807011,-89.6950240945381",
    "latitude": 21.0052077807011,
    "longitude": -89.6950240945381,
    "mapsUrl": "https://www.google.com/maps/place/21%C2%B000'18.8%22N+89%C2%B041'42.1%22W/@21.0052091,-89.6956678,19z/data=!3m1!4b1!4m4!3m3!8m2!3d21.0052078!4d-89.6950241!5m1!1e1?hl=es&entry=ttu&g_ep=EgoyMDI1MTExMS4wIKXMDSoASAFQAw%3D%3D",
    "status": "Disponible",
    "commercialStatus": "EN RENTA",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 8023976.46,
    "cadastralValueM2": 18879.94461,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 1059-UNION",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 32",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-031-local-2",
    "name": "LOCAL 2",
    "projectId": "",
    "type": "LOCAL PLAZA FARO",
    "area": 71,
    "location": "#650 CALLE 31 FRACCIONAMIENTO CIUDAD CAUCEL",
    "address": "#650 CALLE 31 FRACCIONAMIENTO CIUDAD CAUCEL",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 113013.753,
    "coordinates": "21.0052077807011,-89.6950240945381",
    "latitude": 21.0052077807011,
    "longitude": -89.6950240945381,
    "mapsUrl": "https://www.google.com/maps/place/21%C2%B000'18.8%22N+89%C2%B041'42.1%22W/@21.0052091,-89.6956678,19z/data=!3m1!4b1!4m4!3m3!8m2!3d21.0052078!4d-89.6950241!5m1!1e1?hl=es&entry=ttu&g_ep=EgoyMDI1MTExMS4wIKXMDSoASAFQAw%3D%3D",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 8023976.46,
    "cadastralValueM2": 113013.753,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 1059-UNION",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": 2023,
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 33",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-032-local-3",
    "name": "LOCAL 3",
    "projectId": "",
    "type": "LOCAL PLAZA FARO",
    "area": 50.5,
    "location": "#650 CALLE 31 FRACCIONAMIENTO CIUDAD CAUCEL",
    "address": "#650 CALLE 31 FRACCIONAMIENTO CIUDAD CAUCEL",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 158890.623,
    "coordinates": "21.0052077807011,-89.6950240945381",
    "latitude": 21.0052077807011,
    "longitude": -89.6950240945381,
    "mapsUrl": "https://www.google.com/maps/place/21%C2%B000'18.8%22N+89%C2%B041'42.1%22W/@21.0052091,-89.6956678,19z/data=!3m1!4b1!4m4!3m3!8m2!3d21.0052078!4d-89.6950241!5m1!1e1?hl=es&entry=ttu&g_ep=EgoyMDI1MTExMS4wIKXMDSoASAFQAw%3D%3D",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 8023976.46,
    "cadastralValueM2": 158890.623,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 1059-UNION",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": 2023,
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 34",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-033-local-4",
    "name": "LOCAL 4",
    "projectId": "",
    "type": "LOCAL PLAZA FARO",
    "area": 50.5,
    "location": "#650 CALLE 31 FRACCIONAMIENTO CIUDAD CAUCEL",
    "address": "#650 CALLE 31 FRACCIONAMIENTO CIUDAD CAUCEL",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 158890.623,
    "coordinates": "21.0052077807011,-89.6950240945381",
    "latitude": 21.0052077807011,
    "longitude": -89.6950240945381,
    "mapsUrl": "https://www.google.com/maps/place/21%C2%B000'18.8%22N+89%C2%B041'42.1%22W/@21.0052091,-89.6956678,19z/data=!3m1!4b1!4m4!3m3!8m2!3d21.0052078!4d-89.6950241!5m1!1e1?hl=es&entry=ttu&g_ep=EgoyMDI1MTExMS4wIKXMDSoASAFQAw%3D%3D",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 8023976.46,
    "cadastralValueM2": 158890.623,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 1059-UNION",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": 2023,
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 35",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-034-local-5",
    "name": "LOCAL 5",
    "projectId": "",
    "type": "LOCAL PLAZA FARO",
    "area": 50.5,
    "location": "#650 CALLE 31 FRACCIONAMIENTO CIUDAD CAUCEL",
    "address": "#650 CALLE 31 FRACCIONAMIENTO CIUDAD CAUCEL",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 158890.623,
    "coordinates": "21.0052077807011,-89.6950240945381",
    "latitude": 21.0052077807011,
    "longitude": -89.6950240945381,
    "mapsUrl": "https://www.google.com/maps/place/21%C2%B000'18.8%22N+89%C2%B041'42.1%22W/@21.0052091,-89.6956678,19z/data=!3m1!4b1!4m4!3m3!8m2!3d21.0052078!4d-89.6950241!5m1!1e1?hl=es&entry=ttu&g_ep=EgoyMDI1MTExMS4wIKXMDSoASAFQAw%3D%3D",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 8023976.46,
    "cadastralValueM2": 158890.623,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 1059-UNION",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": 2023,
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 36",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-035-local-6",
    "name": "LOCAL 6",
    "projectId": "",
    "type": "LOCAL PLAZA FARO",
    "area": 71,
    "location": "#650 CALLE 31 FRACCIONAMIENTO CIUDAD CAUCEL",
    "address": "#650 CALLE 31 FRACCIONAMIENTO CIUDAD CAUCEL",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 113013.753,
    "coordinates": "21.0052077807011,-89.6950240945381",
    "latitude": 21.0052077807011,
    "longitude": -89.6950240945381,
    "mapsUrl": "https://www.google.com/maps/place/21%C2%B000'18.8%22N+89%C2%B041'42.1%22W/@21.0052091,-89.6956678,19z/data=!3m1!4b1!4m4!3m3!8m2!3d21.0052078!4d-89.6950241!5m1!1e1?hl=es&entry=ttu&g_ep=EgoyMDI1MTExMS4wIKXMDSoASAFQAw%3D%3D",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 8023976.46,
    "cadastralValueM2": 113013.753,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 1059-UNION",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": 2023,
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 37",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-036-local-7",
    "name": "LOCAL 7",
    "projectId": "",
    "type": "LOCAL PLAZA FARO",
    "area": 103.6,
    "location": "#650 CALLE 31 FRACCIONAMIENTO CIUDAD CAUCEL",
    "address": "#650 CALLE 31 FRACCIONAMIENTO CIUDAD CAUCEL",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 77451.51023,
    "coordinates": "21.0052077807011,-89.6950240945381",
    "latitude": 21.0052077807011,
    "longitude": -89.6950240945381,
    "mapsUrl": "https://www.google.com/maps/place/21%C2%B000'18.8%22N+89%C2%B041'42.1%22W/@21.0052091,-89.6956678,19z/data=!3m1!4b1!4m4!3m3!8m2!3d21.0052078!4d-89.6950241!5m1!1e1?hl=es&entry=ttu&g_ep=EgoyMDI1MTExMS4wIKXMDSoASAFQAw%3D%3D",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 8023976.46,
    "cadastralValueM2": 77451.51023,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 1059-UNION",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": 2023,
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 38",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-037-local-8",
    "name": "LOCAL 8",
    "projectId": "",
    "type": "LOCAL PLAZA FARO",
    "area": 208.6,
    "location": "#650 CALLE 31 FRACCIONAMIENTO CIUDAD CAUCEL",
    "address": "#650 CALLE 31 FRACCIONAMIENTO CIUDAD CAUCEL",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 38465.85072,
    "coordinates": "21.0052077807011,-89.6950240945381",
    "latitude": 21.0052077807011,
    "longitude": -89.6950240945381,
    "mapsUrl": "https://www.google.com/maps/place/21%C2%B000'18.8%22N+89%C2%B041'42.1%22W/@21.0052091,-89.6956678,19z/data=!3m1!4b1!4m4!3m3!8m2!3d21.0052078!4d-89.6950241!5m1!1e1?hl=es&entry=ttu&g_ep=EgoyMDI1MTExMS4wIKXMDSoASAFQAw%3D%3D",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 8023976.46,
    "cadastralValueM2": 38465.85072,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 1059-UNION",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": 2023,
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 39",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-038-local-9",
    "name": "LOCAL 9",
    "projectId": "",
    "type": "LOCAL PLAZA FARO",
    "area": 208.6,
    "location": "#650 CALLE 31 FRACCIONAMIENTO CIUDAD CAUCEL",
    "address": "#650 CALLE 31 FRACCIONAMIENTO CIUDAD CAUCEL",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 38465.85072,
    "coordinates": "21.0052077807011,-89.6950240945381",
    "latitude": 21.0052077807011,
    "longitude": -89.6950240945381,
    "mapsUrl": "https://www.google.com/maps/place/21%C2%B000'18.8%22N+89%C2%B041'42.1%22W/@21.0052091,-89.6956678,19z/data=!3m1!4b1!4m4!3m3!8m2!3d21.0052078!4d-89.6950241!5m1!1e1?hl=es&entry=ttu&g_ep=EgoyMDI1MTExMS4wIKXMDSoASAFQAw%3D%3D",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 8023976.46,
    "cadastralValueM2": 38465.85072,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 1059-UNION",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": 2023,
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 40",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-039-local-10",
    "name": "LOCAL 10",
    "projectId": "",
    "type": "LOCAL PLAZA FARO",
    "area": 85.7,
    "location": "#650 CALLE 31 FRACCIONAMIENTO CIUDAD CAUCEL",
    "address": "#650 CALLE 31 FRACCIONAMIENTO CIUDAD CAUCEL",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 93628.66348,
    "coordinates": "21.0052077807011,-89.6950240945381",
    "latitude": 21.0052077807011,
    "longitude": -89.6950240945381,
    "mapsUrl": "https://www.google.com/maps/place/21%C2%B000'18.8%22N+89%C2%B041'42.1%22W/@21.0052091,-89.6956678,19z/data=!3m1!4b1!4m4!3m3!8m2!3d21.0052078!4d-89.6950241!5m1!1e1?hl=es&entry=ttu&g_ep=EgoyMDI1MTExMS4wIKXMDSoASAFQAw%3D%3D",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 8023976.46,
    "cadastralValueM2": 93628.66348,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 1059-UNION",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": 2023,
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 41",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-040-cartoleria-y-distribuidora-del-sureste",
    "name": "CARTOLERIA Y DISTRIBUIDORA DEL SURESTE",
    "projectId": "",
    "type": "Casa",
    "area": 160,
    "location": "#223 C. 13 FRACC EL PRADO",
    "address": "#223 C. 13 FRACC EL PRADO",
    "state": "YUCATAN",
    "cadastralId": "",
    "rentalPrice": 0,
    "pricePerM2": 2285,
    "coordinates": "21.0210837421487,-89.6397309835893",
    "latitude": 21.0210837421487,
    "longitude": -89.6397309835893,
    "mapsUrl": "https://maps.app.goo.gl/XEGuHxtUsPr7wuRJA",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Revisar antes de cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 365600,
    "cadastralValueM2": 2285,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 67",
    "hasCadastralCertificate": "",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Revisar antes de cargar",
    "requiresReview": true,
    "reviewNotes": "Falta cédula",
    "notes": "Origen Excel fila 42",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-041-terreno-vacio-alado-de-farmacia-guadalajara",
    "name": "TERRENO VACIO ALADO DE FARMACIA GUADALAJARA",
    "projectId": "",
    "type": "Terreno",
    "area": 450,
    "location": "#529 A C. 59 A FRACC. PASEO DE LAS FUENTES",
    "address": "#529 A C. 59 A FRACC. PASEO DE LAS FUENTES",
    "state": "YUCATAN",
    "cadastralId": "",
    "rentalPrice": 0,
    "pricePerM2": 2470,
    "coordinates": "20.9798361619944,-89.6470434349454",
    "latitude": 20.9798361619944,
    "longitude": -89.6470434349454,
    "mapsUrl": "https://goo.gl/maps/MeUwcifgQA53QAwu7",
    "status": "Disponible",
    "commercialStatus": "EN RENTA",
    "legalStatus": "Revisar antes de cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 1111500,
    "cadastralValueM2": 2470,
    "commercialValueEstimate": 0,
    "purchaseDeed": "",
    "hasCadastralCertificate": "",
    "hasPlan": "",
    "lastPredialPayment": "",
    "importStatus": "Revisar antes de cargar",
    "requiresReview": true,
    "reviewNotes": "Falta escritura; Falta cédula; Falta plano",
    "notes": "Origen Excel fila 43",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-042-plaza-aura",
    "name": "PLAZA AURA",
    "projectId": "",
    "type": "Terreno",
    "area": 4025,
    "location": "#638 CALLE  51 CAUCEL",
    "address": "#638 CALLE  51 CAUCEL",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 2655,
    "coordinates": "21.0006612576861,-89.7090185453379",
    "latitude": 21.0006612576861,
    "longitude": -89.7090185453379,
    "mapsUrl": "https://maps.app.goo.gl/nafUYf4SEZnyKXh69",
    "status": "En desarrollo",
    "commercialStatus": "PLAZA",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 10686375,
    "cadastralValueM2": 2655,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 145",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 44",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-043-plaza-aura-636-calle-51-caucel",
    "name": "PLAZA AURA - 636 CALLE 51 CAUCEL",
    "projectId": "",
    "type": "Terreno",
    "area": 1000,
    "location": "#636 CALLE 51 CAUCEL",
    "address": "#636 CALLE 51 CAUCEL",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 2655,
    "coordinates": "21.0008287153468,-89.7090303461491",
    "latitude": 21.0008287153468,
    "longitude": -89.7090303461491,
    "mapsUrl": "https://maps.app.goo.gl/p9NW8nrEVfZLtmui6",
    "status": "En desarrollo",
    "commercialStatus": "PLAZA",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 2655000,
    "cadastralValueM2": 2655,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 293",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "SI",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 45",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-044-plaza-aura-634-calle-51-caucel",
    "name": "PLAZA AURA - 634 CALLE 51 CAUCEL",
    "projectId": "",
    "type": "Terreno",
    "area": 1000,
    "location": "#634 CALLE 51 CAUCEL",
    "address": "#634 CALLE 51 CAUCEL",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 2655,
    "coordinates": "21.001082104871,-89.7090657485827",
    "latitude": 21.001082104871,
    "longitude": -89.7090657485827,
    "mapsUrl": "https://maps.app.goo.gl/ZUBijhzAmKVSZNgf8",
    "status": "En desarrollo",
    "commercialStatus": "PLAZA",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 2655000,
    "cadastralValueM2": 2655,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 293",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "SI",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 46",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-045-plaza-aura-632-calle-51-caucel",
    "name": "PLAZA AURA - 632 CALLE 51 CAUCEL",
    "projectId": "",
    "type": "Terreno",
    "area": 1000,
    "location": "#632 CALLE 51 CAUCEL",
    "address": "#632 CALLE 51 CAUCEL",
    "state": "YUCATAN",
    "cadastralId": "",
    "rentalPrice": 0,
    "pricePerM2": 2655,
    "coordinates": "21.0011878673277,-89.7089170583616",
    "latitude": 21.0011878673277,
    "longitude": -89.7089170583616,
    "mapsUrl": "https://maps.app.goo.gl/XR8yFtgheyKVLkwCA",
    "status": "En desarrollo",
    "commercialStatus": "PLAZA",
    "legalStatus": "Revisar antes de cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 2655000,
    "cadastralValueM2": 2655,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 546",
    "hasCadastralCertificate": "",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Revisar antes de cargar",
    "requiresReview": true,
    "reviewNotes": "Falta cédula",
    "notes": "Origen Excel fila 47",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-046-orion-bussines",
    "name": "ORION BUSSINES",
    "projectId": "",
    "type": "Terreno",
    "area": 2065,
    "location": "#306 C. 11 COLONIA SANTA GERTRUDIS COPO",
    "address": "#306 C. 11 COLONIA SANTA GERTRUDIS COPO",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 4394.673123,
    "coordinates": "21.0351263502415,-89.5931253381843",
    "latitude": 21.0351263502415,
    "longitude": -89.5931253381843,
    "mapsUrl": "https://maps.app.goo.gl/dgA4yioFeQyPgH3A9",
    "status": "Disponible",
    "commercialStatus": "EN RENTA",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 9075000,
    "cadastralValueM2": 4394.673123,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 497",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 48",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-047-orion-bussines",
    "name": "ORION BUSSINES",
    "projectId": "",
    "type": "Terreno",
    "area": 2016,
    "location": "308 C. 11 COLONIA SANTA GERTRUDIS COPO",
    "address": "308 C. 11 COLONIA SANTA GERTRUDIS COPO",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 4395,
    "coordinates": "21.0353942664807,-89.5933161669846",
    "latitude": 21.0353942664807,
    "longitude": -89.5933161669846,
    "mapsUrl": "https://maps.app.goo.gl/dgA4yioFeQyPgH3A9",
    "status": "Disponible",
    "commercialStatus": "EN RENTA",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 8860320,
    "cadastralValueM2": 4395,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 603",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 49",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-048-terreno-cancun",
    "name": "TERRENO CANCUN",
    "projectId": "",
    "type": "Terreno",
    "area": 0,
    "location": "pedir info a jesus delgado",
    "address": "pedir info a jesus delgado",
    "state": "YUCATAN",
    "cadastralId": "",
    "rentalPrice": 0,
    "pricePerM2": 0,
    "coordinates": "",
    "latitude": "",
    "longitude": "",
    "mapsUrl": "",
    "status": "Disponible",
    "commercialStatus": "EN RENTA",
    "legalStatus": "Revisar antes de cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 0,
    "cadastralValueM2": 0,
    "commercialValueEstimate": 0,
    "purchaseDeed": "",
    "hasCadastralCertificate": "",
    "hasPlan": "",
    "lastPredialPayment": "",
    "importStatus": "Revisar antes de cargar",
    "requiresReview": true,
    "reviewNotes": "Faltan coordenadas; Falta escritura; Falta cédula; Falta plano",
    "notes": "Origen Excel fila 50",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-049-sodzil-norte",
    "name": "SODZIL NORTE",
    "projectId": "",
    "type": "Terreno",
    "area": 616,
    "location": "#359 C. 31 COLONIA SODZIL NORTE",
    "address": "#359 C. 31 COLONIA SODZIL NORTE",
    "state": "YUCATAN",
    "cadastralId": "2024",
    "rentalPrice": 0,
    "pricePerM2": 2565,
    "coordinates": "21.042344772317,-89.6263636250712",
    "latitude": 21.042344772317,
    "longitude": -89.6263636250712,
    "mapsUrl": "https://maps.app.goo.gl/hSxs6SPYpZWwARv46",
    "status": "Disponible",
    "commercialStatus": "EN RENTA",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 1580040,
    "cadastralValueM2": 2565,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 53",
    "hasCadastralCertificate": "2024",
    "hasPlan": "2024",
    "lastPredialPayment": 2024,
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 51",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-050-william-herrera",
    "name": "WILLIAM HERRERA",
    "projectId": "",
    "type": "Casa",
    "area": 160,
    "location": "#41 C. 14 COLONIA CHUBURNA DE HIDALGO",
    "address": "#41 C. 14 COLONIA CHUBURNA DE HIDALGO",
    "state": "YUCATAN",
    "cadastralId": "",
    "rentalPrice": 0,
    "pricePerM2": 1505,
    "coordinates": "21.0016921367575,-89.6258178206816",
    "latitude": 21.0016921367575,
    "longitude": -89.6258178206816,
    "mapsUrl": "https://maps.app.goo.gl/yZGYZZf8XTseswEE8",
    "status": "Ocupado",
    "commercialStatus": "RENTADO",
    "legalStatus": "Revisar antes de cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 240800,
    "cadastralValueM2": 1505,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 251",
    "hasCadastralCertificate": "",
    "hasPlan": "SI",
    "lastPredialPayment": 2024,
    "importStatus": "Revisar antes de cargar",
    "requiresReview": true,
    "reviewNotes": "Falta cédula",
    "notes": "Origen Excel fila 52",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-051-gran-plaza",
    "name": "GRAN PLAZA",
    "projectId": "",
    "type": "Local comercial",
    "area": 146.01,
    "location": "#190 C. 75 COLONIA MONTES DE AME- LOCAL 205",
    "address": "#190 C. 75 COLONIA MONTES DE AME- LOCAL 205",
    "state": "YUCATAN",
    "cadastralId": "",
    "rentalPrice": 0,
    "pricePerM2": 6435.175673,
    "coordinates": "21.0292790300349,-89.6256140336769",
    "latitude": 21.0292790300349,
    "longitude": -89.6256140336769,
    "mapsUrl": "https://maps.app.goo.gl/k9QYxebg8DBxnf6JA",
    "status": "Disponible",
    "commercialStatus": "DISPONIBLE",
    "legalStatus": "Revisar antes de cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 939600,
    "cadastralValueM2": 6435.175673,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 2326",
    "hasCadastralCertificate": "",
    "hasPlan": "",
    "lastPredialPayment": "",
    "importStatus": "Revisar antes de cargar",
    "requiresReview": true,
    "reviewNotes": "Falta cédula; Falta plano",
    "notes": "Origen Excel fila 53",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-052-terreno-dzitya-enfrente-a-campocielo",
    "name": "TERRENO DZITYA ENFRENTE A CAMPOCIELO",
    "projectId": "",
    "type": "Terreno",
    "area": 1298.72,
    "location": "CALLE #71 544X  68 Y 68 A COL DZITYA POLIGONO CHUBURNA",
    "address": "CALLE #71 544X  68 Y 68 A COL DZITYA POLIGONO CHUBURNA",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 565,
    "coordinates": "21.0572450571987,-89.6394088889476",
    "latitude": 21.0572450571987,
    "longitude": -89.6394088889476,
    "mapsUrl": "https://maps.app.goo.gl/yKEbxs4qUqgsRQnz7",
    "status": "Disponible",
    "commercialStatus": "DISPONIBLE",
    "legalStatus": "Listo para cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 733776.8,
    "cadastralValueM2": 565,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 1854",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Listo para cargar",
    "requiresReview": false,
    "reviewNotes": "",
    "notes": "Origen Excel fila 54",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-053-terreno-dzitya-2-enfrente-a-campocielo",
    "name": "TERRENO DZITYA 2 ENFRENTE A CAMPOCIELO",
    "projectId": "",
    "type": "Terreno",
    "area": 1498.73,
    "location": "CALLE #71 546 X 68 Y 68 A COL DZITYA POLIGONO CHUBURNA",
    "address": "CALLE #71 546 X 68 Y 68 A COL DZITYA POLIGONO CHUBURNA",
    "state": "YUCATAN",
    "cadastralId": "SI",
    "rentalPrice": 0,
    "pricePerM2": 564.9679595,
    "coordinates": "21.0571681040794,-89.6397241756291",
    "latitude": 21.0571681040794,
    "longitude": -89.6397241756291,
    "mapsUrl": "https://maps.app.goo.gl/bgnQ7kipLKvJ95PB8",
    "status": "Revisión pendiente",
    "commercialStatus": "PENDIENTE",
    "legalStatus": "Revisar antes de cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 846734.43,
    "cadastralValueM2": 564.9679595,
    "commercialValueEstimate": 0,
    "purchaseDeed": "ACTA 1854",
    "hasCadastralCertificate": "SI",
    "hasPlan": "SI",
    "lastPredialPayment": "",
    "importStatus": "Revisar antes de cargar",
    "requiresReview": true,
    "reviewNotes": "Falta estatus",
    "notes": "Origen Excel fila 55",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-054-agreagar-2-casas-del-centro-que-renta-eladios-centro-aparte-",
    "name": "AGREAGAR 2 CASAS DEL CENTRO QUE RENTA ELADIOS CENTRO APARTE QUE SON PARTE DEL ESTACIONAMIENTO",
    "projectId": "",
    "type": "Pendiente definir",
    "area": 0,
    "location": "",
    "address": "",
    "state": "YUCATAN",
    "cadastralId": "",
    "rentalPrice": 0,
    "pricePerM2": 0,
    "coordinates": "",
    "latitude": "",
    "longitude": "",
    "mapsUrl": "",
    "status": "Revisión pendiente",
    "commercialStatus": "PENDIENTE",
    "legalStatus": "Revisar antes de cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 0,
    "cadastralValueM2": 0,
    "commercialValueEstimate": 0,
    "purchaseDeed": "",
    "hasCadastralCertificate": "",
    "hasPlan": "",
    "lastPredialPayment": "",
    "importStatus": "Revisar antes de cargar",
    "requiresReview": true,
    "reviewNotes": "Falta dirección; Falta tipo; Falta estatus; Faltan coordenadas; Falta escritura; Falta cédula; Falta plano",
    "notes": "Origen Excel fila 56",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-055-predio-alado-de-oficina-de-eladios",
    "name": "PREDIO ALADO DE OFICINA DE ELADIOS",
    "projectId": "",
    "type": "Pendiente definir",
    "area": 0,
    "location": "",
    "address": "",
    "state": "YUCATAN",
    "cadastralId": "",
    "rentalPrice": 0,
    "pricePerM2": 0,
    "coordinates": "",
    "latitude": "",
    "longitude": "",
    "mapsUrl": "",
    "status": "Revisión pendiente",
    "commercialStatus": "PENDIENTE",
    "legalStatus": "Revisar antes de cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 0,
    "cadastralValueM2": 0,
    "commercialValueEstimate": 0,
    "purchaseDeed": "",
    "hasCadastralCertificate": "",
    "hasPlan": "",
    "lastPredialPayment": "",
    "importStatus": "Revisar antes de cargar",
    "requiresReview": true,
    "reviewNotes": "Falta dirección; Falta tipo; Falta estatus; Faltan coordenadas; Falta escritura; Falta cédula; Falta plano",
    "notes": "Origen Excel fila 57",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  },
  {
    "id": "INM-056-estacionamiento-de-eladios-de-oriente-deben-ser-dos-terrenos",
    "name": "ESTACIONAMIENTO DE ELADIOS DE ORIENTE DEBEN SER DOS TERRENOS",
    "projectId": "",
    "type": "Pendiente definir",
    "area": 0,
    "location": "",
    "address": "",
    "state": "YUCATAN",
    "cadastralId": "",
    "rentalPrice": 0,
    "pricePerM2": 0,
    "coordinates": "",
    "latitude": "",
    "longitude": "",
    "mapsUrl": "",
    "status": "Revisión pendiente",
    "commercialStatus": "PENDIENTE",
    "legalStatus": "Revisar antes de cargar",
    "ownerId": "PROP-LFHV",
    "ownerName": "Luis Felipe Herrera Vázquez",
    "depositAccountId": "",
    "depositAccountAlias": "Pendiente asignar cuenta",
    "cadastralValue": 0,
    "cadastralValueM2": 0,
    "commercialValueEstimate": 0,
    "purchaseDeed": "",
    "hasCadastralCertificate": "",
    "hasPlan": "",
    "lastPredialPayment": "",
    "importStatus": "Revisar antes de cargar",
    "requiresReview": true,
    "reviewNotes": "Falta dirección; Falta tipo; Falta estatus; Faltan coordenadas; Falta escritura; Falta cédula; Falta plano",
    "notes": "Origen Excel fila 58",
    "attachments": [],
    "source": "Relación de Inmuebles Luis Felipe Herrera Vazquez (2).xlsx"
  }
];
