// Contenido oficial extraido de los manuales de calidad de Triton Desarrollos.
// TR-AC-M01 Manual de Aseguramiento de Calidad durante la Ejecucion de Obra (V-01)
// TR-CC-M01 Manual de Control de Calidad para Entrega de Vivienda (V-01)
// Estos arreglos son solo la SEMILLA inicial: una vez cargados en qualitySpecs,
// el equipo de Triton puede editarlos, agregar o quitar puntos desde Configurar obra.
// Las imagenes de referencia viven en /public/quality-base/<manual>/<clave>.jpg
// (paginas del manual renderizadas), con su manifest.json correspondiente.

export const partidaTemplates = [
  { id: "preliminares", name: "Preliminares", weight: 5 },
  { id: "excavacion", name: "Excavación", weight: 5 },
  { id: "cimentacion", name: "Cimentación", weight: 10 },
  { id: "colado", name: "Colado", weight: 5 },
  { id: "estructura", name: "Estructura", weight: 10 },
  { id: "losa", name: "Losa", weight: 5 },
  { id: "albanileria", name: "Albañilería", weight: 10 },
  { id: "hidraulicas", name: "Hidráulicas", weight: 5 },
  { id: "electricas", name: "Eléctricas", weight: 5 },
  { id: "aplanados", name: "Aplanados", weight: 5 },
  { id: "pisos", name: "Pisos", weight: 10 },
  { id: "impermeabilizante", name: "Impermeabilizante", weight: 5 },
  { id: "canceleria", name: "Cancelería", weight: 5 },
  { id: "general", name: "General", weight: 5 },
];

export const zonaTemplates = [
  { id: "fachada", name: "Fachada", weight: 1 },
  { id: "patio", name: "Patio / Exterior", weight: 1 },
  { id: "sala_comedor", name: "Sala / Comedor", weight: 1 },
  { id: "cocina", name: "Cocina", weight: 1 },
  { id: "recamaras", name: "Recámaras", weight: 1 },
  { id: "banos", name: "Baños", weight: 1 },
  { id: "piscina", name: "Piscina", weight: 1 },
  { id: "azotea", name: "Azotea", weight: 1 },
  { id: "senalizacion", name: "Señalización", weight: 1 },
];

export const zonaAliases = {
  "FA": "fachada",
  "PE": "patio",
  "SC": "sala_comedor",
  "CN": "cocina",
  "RE": "recamaras",
  "BA": "banos",
  "PI": "piscina",
  "AZ": "azotea",
  "SÑ": "senalizacion",
  "SN": "senalizacion",
};

export function zonaIdFromCode(code = "") {
  const prefix = String(code).split("-")[1];
  return zonaAliases[prefix] || "general";
}

export const aseguramientoManualSpecs = [
  {
    clave: "AC-PL-01",
    concepto: "El trazo coincide con planos autorizados",
    criterioAceptacion: "El trazo deberá corresponder exactamente a la ubicación, ejes, dimensiones y alineaciones indicadas en planos arquitectónicos y estructurales vigentes.",
    formaVerificacion: "Medir distancias entre ejes principales. Confirmar escuadra general mediante verificación diagonal. Comparar medidas críticas con plano autorizado.",
    puntosAceptables: "Las dimensiones coinciden con plano. La escuadra es correcta. Los ejes están claramente definidos y alineados.",
    puntosNoAceptables: "Existen desviaciones dimensionales respecto al plano. La escuadra no coincide. Los ejes no están correctamente alineados. Se detectan diferencias en ubicación del desplante.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-PL-01.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-PL-02",
    concepto: "Los niveles de desplante fueron verificados",
    criterioAceptacion: "El nivel de desplante deberá coincidir con la cota establecida en proyecto, considerando referencia topográfica o banco de nivel autorizado.",
    formaVerificacion: "Comprobar nivel mediante equipo de medición. Verificar relación entre nivel natural del terreno y nivel proyectado.",
    puntosAceptables: "El nivel coincide con la cota indicada. Se mantiene referencia clara de banco de nivel. Las pendientes proyectadas están correctamente ejecutadas.",
    puntosNoAceptables: "Existe diferencia significativa respecto a la cota de proyecto. No se cuenta con referencia de nivel confiable. Se detectan pendientes no contempladas.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-PL-02.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-PL-03",
    concepto: "Ejes y referencias se encuentran protegidos",
    criterioAceptacion: "Las referencias de trazo deberán permanecer visibles y protegidas durante la ejecución para evitar pérdida de alineación estructural.",
    formaVerificacion: "Inspeccionar puntos de control. Confirmar que no hayan sido alterados por movimiento de maquinaria o material.",
    puntosAceptables: "Las referencias están claramente marcadas. Permanecen protegidas y visibles. No presentan alteraciones.",
    puntosNoAceptables: "Las referencias han sido borradas o desplazadas. No existen puntos de control activos. Se pierde alineación original.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-PL-03.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-EX-01",
    concepto: "Profundidad y dimensiones de excavación cumplen especificación",
    criterioAceptacion: "Las excavaciones deberán ejecutarse conforme a dimensiones y profundidad establecidas en planos estructurales.",
    formaVerificacion: "Medir profundidad en distintos puntos. Verificar ancho y longitud de zanjas o dados antes de armado.",
    puntosAceptables: "Dimensiones coinciden con plano. La excavación es uniforme. Las paredes se encuentran estables.",
    puntosNoAceptables: "La profundidad es menor a la especificada. Existen variaciones dimensionales no autorizadas. Se detectan paredes inestables o colapsadas.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-EX-01.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-EX-02",
    concepto: "Fondo de excavación firme y libre de material suelto",
    criterioAceptacion: "El fondo deberá estar limpio, compacto y libre de material orgánico o suelto antes de colocar plantilla o armado.",
    formaVerificacion: "Inspección visual y comprobación de firmeza. Confirmar retiro de material suelto previo a colado de plantilla.",
    puntosAceptables: "El fondo está firme y compacto. Se encuentra limpio. No hay material inadecuado presente.",
    puntosNoAceptables: "Existen capas de material suelto. Se observa humedad excesiva no controlada. Hay presencia de raíces o residuos orgánicos.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-EX-02.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-CI-01",
    concepto: "Plantilla de concreto aplicada antes de armado",
    criterioAceptacion: "La plantilla deberá aplicarse con espesor uniforme antes de colocar acero de refuerzo, garantizando separación adecuada del suelo natural.",
    formaVerificacion: "Confirmar presencia de plantilla y revisar espesor aproximado antes del armado.",
    puntosAceptables: "La plantilla está presente y uniforme. El acero no tiene contacto directo con el. suelo. La superficie es adecuada para el armado.",
    puntosNoAceptables: "No existe plantilla. El espesor es irregular o insuficiente. El acero queda en contacto directo con el terreno.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-CI-01.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-CI-02",
    concepto: "Acero de refuerzo conforme a diámetro y separación especificados",
    criterioAceptacion: "El acero de refuerzo deberá corresponder al diámetro, cantidad, ubicación y separación indicados en planos estructurales.",
    formaVerificacion: "Revisar visualmente el diámetro de varillas. Medir separación entre barras. Confirmar ubicación correcta antes del colado.",
    puntosAceptables: "El diámetro es el especificado. La separación cumple con plano. El armado coincide en cantidad y ubicación.",
    puntosNoAceptables: "El diámetro no coincide con el especificado. La separación entre barras es distinta a la indicada. Existen barras faltantes. La colocación no corresponde al plano estructural.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-CI-02.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-CI-03",
    concepto: "Traslapes y amarres correctamente ejecutados",
    criterioAceptacion: "Los traslapes deberán cumplir con la longitud mínima requerida y los amarres deberán asegurar estabilidad del armado previo al colado.",
    formaVerificacion: "Medir longitud de traslapes en puntos representativos. Verificar firmeza del amarre y continuidad estructural.",
    puntosAceptables: "Los traslapes cumplen longitud mínima. Los amarres aseguran estabilidad. El armado se mantiene firme.",
    puntosNoAceptables: "La longitud de traslape es insuficiente. Los amarres son escasos o inexistentes. El armado presenta inestabilidad.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-CI-03.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-CI-04",
    concepto: "Recubrimiento mínimo de concreto respetado",
    criterioAceptacion: "El acero deberá mantener el recubrimiento mínimo especificado para evitar exposición o corrosión futura.",
    formaVerificacion: "Confirmar colocación de separadores. Medir distancia aproximada entre acero y cimbra o plantilla.",
    puntosAceptables: "El acero mantiene separación uniforme. Existen separadores correctamente colocados. El recubrimiento cumple con especificación.",
    puntosNoAceptables: "El acero se encuentra en contacto con la cimbra o terreno. No existen separadores. El recubrimiento es insuficiente.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-CI-04.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-CI-05",
    concepto: "Instalaciones cruzando cimentación protegidas",
    criterioAceptacion: "Las tuberías o ductos que atraviesen elementos de cimentación deberán encontrarse correctamente protegidos y ubicados conforme a plano.",
    formaVerificacion: "Confirmar ubicación previa al colado. Verificar protección y fijación adecuada.",
    puntosAceptables: "La ubicación coincide con plano. Se encuentran protegidas. Están firmemente fijadas.",
    puntosNoAceptables: "Las instalaciones no coinciden con ubicación proyectada. No cuentan con protección. Presentan desplazamiento previo al colado.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-CI-05.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-CO-01",
    concepto: "Concreto con revenimiento adecuado",
    criterioAceptacion: "El concreto deberá presentar consistencia adecuada conforme a especificación técnica, sin exceso de agua.",
    formaVerificacion: "Observar consistencia al momento del vaciado. Confirmar que no se agregue agua adicional en obra sin autorización técnica.",
    puntosAceptables: "La consistencia es uniforme. No hay segregación visible. Se respeta la dosificación indicada.",
    puntosNoAceptables: "Se observa segregación. Se adiciona agua en exceso. La mezcla es excesivamente fluida o seca.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-CO-01.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-CO-02",
    concepto: "Vibrado correcto sin segregación",
    criterioAceptacion: "El concreto deberá vibrarse adecuadamente para evitar vacíos, sin provocar segregación de materiales.",
    formaVerificacion: "Supervisar proceso de vibrado durante colado. Confirmar que el vibrador se utilice correctamente y sin sobreexposición en un solo punto.",
    puntosAceptables: "El concreto se compacta adecuadamente. No existen vacíos visibles. La superficie presenta acabado uniforme posterior al colado.",
    puntosNoAceptables: "Se observan vacíos o nidos de grava. El vibrado es insuficiente. Se produce segregación por vibrado excesivo.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-CO-02.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-CO-03",
    concepto: "Curado aplicado posterior al colado",
    criterioAceptacion: "Los elementos colados deberán recibir curado adecuado para evitar fisuración prematura y pérdida de resistencia.",
    formaVerificacion: "Confirmar aplicación de método de curado (agua, membrana o equivalente) durante el periodo inicial posterior al colado.",
    puntosAceptables: "Se aplica método de curado adecuado. Se mantiene humedad superficial controlada. No existen fisuras atribuibles a secado prematuro.",
    puntosNoAceptables: "No se aplica ningún método de curado. La superficie presenta fisuras por secado prematuro. El curado se interrumpe antes del tiempo mínimo recomendado.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-CO-03.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-ES-01",
    concepto: "Columnas y castillos se encuentran plomados",
    criterioAceptacion: "Los elementos verticales estructurales deberán mantener alineación vertical conforme a tolerancias aceptables.",
    formaVerificacion: "Comprobar plomo mediante herramienta de medición. Revisar alineación antes del fraguado final.",
    puntosAceptables: "El elemento mantiene verticalidad adecuada. No existen desviaciones perceptibles. Se verificó antes de cierre de cimbra.",
    puntosNoAceptables: "Se detectan desviaciones visibles de verticalidad. El elemento presenta inclinación perceptible. No se realizó verificación antes de fraguar.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-ES-01.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-ES-02",
    concepto: "Dalas y trabes respetan dimensiones de proyecto",
    criterioAceptacion: "Las dimensiones de sección deberán corresponder a lo indicado en planos estructurales.",
    formaVerificacion: "Medir ancho y peralte antes del colado o durante la cimbra.",
    puntosAceptables: "Las dimensiones coinciden con plano. La sección es uniforme. No existen deformaciones.",
    puntosNoAceptables: "Las dimensiones son menores a las especificadas. Existen variaciones no autorizadas. La cimbra presenta deformaciones.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-ES-02.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-ES-03",
    concepto: "Cimbra alineada y firme antes de colado",
    criterioAceptacion: "La cimbra deberá encontrarse correctamente alineada, nivelada y firmemente apuntalada antes del vaciado de concreto.",
    formaVerificacion: "Inspeccionar alineación, fijación y estabilidad general antes del colado.",
    puntosAceptables: "La cimbra está firme y estable. Se encuentra correctamente alineada. El apuntalamiento es adecuado.",
    puntosNoAceptables: "La cimbra presenta movimiento. Existe desalineación visible. El apuntalamiento es insuficiente.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-ES-03.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-LO-01",
    concepto: "Instalaciones colocadas antes de colado de losa",
    criterioAceptacion: "Las instalaciones que deban quedar embebidas en losa deberán colocarse y fijarse antes del colado.",
    formaVerificacion: "Confirmar ubicación y fijación previa al vaciado. Verificar coincidencia con plano.",
    puntosAceptables: "Están correctamente ubicadas. Se encuentran firmemente fijadas. Coinciden con planos.",
    puntosNoAceptables: "Las instalaciones no están colocadas. Se encuentran sueltas o desplazadas. No coinciden con proyecto.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-LO-01.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-LO-02",
    concepto: "Espesor de losa conforme a proyecto",
    criterioAceptacion: "El espesor de losa deberá respetar el valor indicado en planos estructurales.",
    formaVerificacion: "Medir espesor en puntos representativos durante el proceso de colado.",
    puntosAceptables: "El espesor es uniforme. Coincide con proyecto. No existen reducciones no autorizadas.",
    puntosNoAceptables: "El espesor es menor al especificado. Existen variaciones significativas. Se detectan zonas con reducción de sección.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-LO-02.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-AL-01",
    concepto: "Muros alineados y plomados",
    criterioAceptacion: "Los muros deberán ejecutarse respetando alineación horizontal y vertical conforme a proyecto arquitectónico.",
    formaVerificacion: "Comprobar alineación con hilo guía o herramienta de medición. Verificar plomo en distintos puntos del muro antes de continuar con niveles superiores. Colocar regla de 2 m o hilo para detectar.",
    puntosAceptables: "de plomo >5 mm en 2 m Desviación de plomo 5 mm en 2 m. < horizontal del paño >5 mm en 2 m. Alineación horizontal del paño 5 mm en 2 m <.",
    puntosNoAceptables: "Desviación. Alineación.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-AL-01.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-AL-02",
    concepto: "Juntas uniformes y correctamente rellenas",
    criterioAceptacion: "Las juntas entre piezas de muro de block deberán presentar espesor uniforme y relleno completo de mortero.",
    formaVerificacion: "Inspeccionar visualmente continuidad del mortero y uniformidad del espesor en distintos tramos del muro.",
    puntosAceptables: "Las juntas son continuas y uniformes. El mortero rellena completamente el espacio. No existen vacíos visibles.",
    puntosNoAceptables: "Existen juntas vacías o parcialmente rellenas. El espesor varía significativamente. Se observan huecos visibles.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-AL-02.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-AL-03",
    concepto: "Vanos conforme a dimensiones de proyecto",
    criterioAceptacion: "Los vanos de puertas y ventanas deberán ejecutarse respetando ancho, altura y alineación indicados en planos.",
    formaVerificacion: "Medir dimensiones del vano antes de colocar marcos o continuar con acabados. Usar molde de vanos para puertas para evitar retrabajos.",
    puntosAceptables: "Las dimensiones coinciden con proyecto. El vano se encuentra alineado y nivelado. No existen desviaciones. Tolerancia de ancho/alto: +/- 5 mm o menos.",
    puntosNoAceptables: "Las dimensiones no coinciden con plano. Existe desalineación en el vano. No se respeta nivel o escuadra. Tolerancia de ancho/alto: +/- 6 mm o más.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-AL-03.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-IH-01",
    concepto: "Prueba de presión en instalaciones hidráulicas antes de tapar",
    criterioAceptacion: "Las instalaciones hidráulicas deberán someterse a una prueba de presión antes de ser cubiertas con aplanados, concreto o cualquier acabado. La prueba deberá realizarse bajo las siguientes condiciones: ● Presión de prueba:90 PSI (6 kg/cm²) ● Duración mínima:24 horas Durante este periodo, el sistema deberá mantener presión constante sin presentar fugas ni caídas. Adicionalmente, deberá generarse unreporte escritode la prueba, el cual deberá estarfirmado por el responsable de supervisión. Nota: La operación normal de la vivienda no deberá superar60 PSI.",
    formaVerificacion: "Presurizar el sistema conforme a los valores establecidos. Monitorear estabilidad de presión durante 24 horas. Inspeccionar visualmente posibles fugas en conexiones y tuberías. Confirmar existencia de reporte documentado firmado por supervisión.",
    puntosAceptables: "La prueba se realizó conforme a presión y tiempo establecidos. No existen fugas ni caídas de presión. El sistema se mantiene estable durante 24 horas. Existe reporte documentado firmado por supervisión.",
    puntosNoAceptables: "No se realizó la prueba de presión. La presión es menor a la especificada o el. tiempo es insuficiente. Existe caída de presión durante el periodo de prueba. Se detectan fugas visibles. No existe reporte o no está firmado por supervisión.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-IH-01.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-IH-02",
    concepto: "Pendientes de drenaje verificadas",
    criterioAceptacion: "Las tuberías de drenaje deberán contar con pendiente suficiente para permitir desalojo adecuado.",
    formaVerificacion: "Confirmar pendiente visualmente antes de cubrir. Verificar alineación y continuidad de la instalación.",
    puntosAceptables: "La pendiente es continua. No existen contrapendientes. La instalación está correctamente alineada.",
    puntosNoAceptables: "Existen tramos sin pendiente. Se detectan contrapendientes. La alineación es irregular.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-IH-02.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-IE-01",
    concepto: "Canalizaciones eléctricas completas antes de aplanado",
    criterioAceptacion: "Todas las canalizaciones eléctricas deberán encontrarse colocadas y fijadas antes de iniciar aplanados.",
    formaVerificacion: "Revisar recorridos conforme a plano eléctrico. Confirmar fijación y ubicación correcta.",
    puntosAceptables: "Todas las canalizaciones están instaladas. Se encuentran firmemente fijadas. Coinciden con plano autorizado.",
    puntosNoAceptables: "Faltan canalizaciones. Existen ductos sueltos. No coinciden con proyecto.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-IE-01.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-IE-02",
    concepto: "Centro de carga correctamente instalado y señalizado",
    criterioAceptacion: "El centro de carga deberá colocarse conforme a la ubicación proyectada, encontrarse firmemente instalado, alineado y con fijación adecuada, además de contar con nombres en pastillas de cada circuito. Adicionalmente, deberá contar conseñalización preventivavisibleque indique consideraciones para futuras instalaciones, incluyendo: ● Aires acondicionados ● Paneles solares ● Equipos eléctricos adicionales La señalización deberá proporcionar información clara que permita evitar sobrecargas o intervenciones incorrectas en el sistema eléctrico.",
    formaVerificacion: "Confirmar ubicación conforme a plano eléctrico. Verificar fijación, alineación y estabilidad del centro de carga. Inspeccionar presencia de señalización preventiva. Validar que la información sea clara, legible y visible.",
    puntosAceptables: "El centro de carga está correctamente ubicado, alineado y fijado. Cuenta con señalización preventiva visible. La información es clara, legible y completa. Permite orientar correctamente futuras. intervenciones.",
    puntosNoAceptables: "El centro de carga no coincide con ubicación proyectada. Presenta fijación deficiente o desalineación. No existe señalización preventiva. La señalización es ilegible, incompleta o. inexistente.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-IE-02.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-AP-01",
    concepto: "Superficie preparada antes de aplicar aplanados",
    criterioAceptacion: "Las superficies deberán encontrarse limpias, libres de polvo, grasa o material suelto antes de la aplicación de aplanados.",
    formaVerificacion: "Inspección visual previa a la aplicación. Confirmar humectación adecuada cuando el procedimiento lo requiera.",
    puntosAceptables: "La superficie está limpia. No hay material suelto. Se aplicó preparación conforme al. procedimiento. Alineacion horizontal del paño: separacion máxima 5 mm contra hilo o regla de 2 m.",
    puntosNoAceptables: "Existen residuos sueltos. La superficie está contaminada. No se realizó preparación previa.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-AP-01.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-AP-02",
    concepto: "Plomos y niveles verificados en aplanados",
    criterioAceptacion: "Los aplanados deberán ejecutarse manteniendo alineación vertical y horizontal conforme a tolerancias aceptables.",
    formaVerificacion: "Colocar regla metálica de aluminio de 2 m en posición vertical sobre el muro y medir con cuña o calibrador la separación máxima en puntos distribuidos (mín. 5 puntos por paño de muro). Repetir la medición en posición horizontal para verificar planeidad. Iluminar la superficie con linterna o celular en ángulo rasante (luz paralela al muro) a 1 metro de distancia para detectar ondulaciones. Verificar ángulos con escuadra de 90° en encuentros entre muros. Inspeccionar visualmente cada encuentro con plafón y marcos de puertas/ventanas. Registrar con fotografía cualquier punto fuera de tolerancia indicando su ubicación.",
    puntosAceptables: "Desviación de plomo ≤5 mm en 2 m. Huella bajo la regla ≤5 mm en cualquier punto medido. Superficie continua sin ondulaciones a 1 m con luz rasante. Espesor aplanado ≥ cm o conforme a especificación Sin fisuras. Encuentros en escuadra y alineados con marcos y plafón.",
    puntosNoAceptables: "Desviación de plomo >5 mm en 2 m. Huella bajo la regla >5 mm. Ondulaciones visibles a 1 m con luz rasante. Fisuras de cualquier tipo sin tratar. Aristas desalineadas con plafón o marcos Espesor aplanado < cm conforme a. especificación.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-AP-02.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-PI-01",
    concepto: "Base nivelada antes de colocación de piso",
    criterioAceptacion: "La superficie base deberá encontrarse limpia, firme y nivelada antes de colocar recubrimientos.",
    formaVerificacion: "Inspeccionar visualmente la base. Confirmar ausencia de polvo o irregularidades.",
    puntosAceptables: "La superficie es uniforme. Está limpia y firme. Se encuentra lista para recibir el recubrimiento.",
    puntosNoAceptables: "Existen desniveles notorios. Hay residuos sueltos. La base presenta fracturas o humedad excesiva.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-PI-01.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-PI-02",
    concepto: "Adhesivo aplicado uniformemente en colocación de piso",
    criterioAceptacion: "El adhesivo deberá aplicarse de forma homogénea, garantizando adherencia adecuada de las piezas.",
    formaVerificacion: "Supervisar aplicación durante instalación. Confirmar cobertura suficiente bajo piezas representativas.",
    puntosAceptables: "La aplicación es uniforme. Se garantiza contacto adecuado. No existen vacíos bajo piezas.",
    puntosNoAceptables: "La aplicación es discontinua. Existen huecos sin adhesivo. Se observa exceso irregular.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-PI-02.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-PI-03",
    concepto: "Colocación de mármol conforme a especificación técnica",
    criterioAceptacion: "La colocación de mármol deberá ejecutarse conforme a las siguientes especificaciones técnicas obligatorias: ● Uso dellana dentada de 10 a 12 mmpara la aplicacióndel adhesivo. ● El adhesivo deberá aplicarse de manera uniforme, garantizando contacto completo entre pieza y base. ● El adhesivono deberá ser excesivo. ● El adhesivono deberá utilizarse como medio para nivelarel firme. Estas condiciones son críticas para asegurar la correcta adherencia, evitar movimientos de piezas y prevenir fallas futuras en el recubrimiento.",
    formaVerificacion: "Inspección directa durante la colocación. Confirmar uso de herramienta adecuada (llana dentada). Verificar uniformidad en la aplicación del adhesivo. Validar que no se utilice adhesivo para corregir desniveles del firme.",
    puntosAceptables: "Se utiliza llana dentada de 10 a 12 mm. La aplicación del adhesivo es uniforme. No existe exceso de material. El firme está previamente nivelado y el adhesivo se usa únicamente para adherencia. Se garantiza contacto completo entre pieza y base.",
    puntosNoAceptables: "No se utiliza llana dentada o es distinta a la especificada. El adhesivo se aplica de forma irregular o discontinua. Se utiliza adhesivo en exceso. Se emplea adhesivo para nivelar el firme. Existen huecos o falta de contacto entre pieza. y base.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-PI-03.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-PI-04",
    concepto: "Preparación de superficies para colocación de mármol",
    criterioAceptacion: "La superficie base deberá prepararse previamente a la colocación de mármol conforme a las siguientes condiciones: ● En áreas húmedas (baños, regaderas): o AplicarSellotex en todo el firmeprevio a la instalación. ● En planta baja: o AplicarSellotex en escuadras perimetrales de 40 cmen contacto con muros. La preparación deberá ejecutarse de forma uniforme, cubriendo completamente las áreas indicadas, con el objetivo de evitar la aparición de salitre y humedad.",
    formaVerificacion: "Inspección visual antes de la colocación del mármol. Confirmar aplicación de Sellotex en las áreas correspondientes. Verificar cobertura completa y uniforme del producto. Validar que la aplicación se realizó previo a la instalación del recubrimiento.",
    puntosAceptables: "Se aplicó Sellotex en todas las áreas indicadas. La cobertura es uniforme y completa. Se respetan los 40 cm perimetrales en planta baja. La preparación se realizó antes de la colocación del mármol.",
    puntosNoAceptables: "No se aplicó Sellotex en las áreas requeridas. La aplicación es parcial o incompleta. No se respetan los 40 cm perimetrales en planta baja. Se realizó la colocación sin preparación. previa.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-PI-04.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-PI-05",
    concepto: "Aplicación de boquilla en recubrimientos de mármol",
    criterioAceptacion: "La aplicación de boquilla en recubrimientos de mármol deberá realizarse48 horas después de la colocación, asegurando que el adhesivo haya alcanzado un fraguado adecuado. El tiempo de aplicación es crítico para garantizar la correcta adherencia y desempeño del sistema. Nota técnica: ● Si se aplica antes: puede haber movimiento de piezas por falta de fraguado del adhesivo. ● Si se aplica después: las juntas pueden contaminarse con polvo. Consecuencias de una mala aplicación: ● Mala adherencia de la boquilla. ● Filtración de humedad. ● Deterioro prematuro del recubrimiento.",
    formaVerificacion: "Confirmar tiempo transcurrido desde la colocación del mármol. Verificar que el adhesivo haya secado antes de la aplicación. Inspeccionar que las juntas se encuentren limpias previo a la aplicación. Supervisar correcta ejecución durante el proceso.",
    puntosAceptables: "La aplicación se realiza después de 48 horas. El adhesivo se encuentra completamente seco. Las piezas están firmes y sin movimiento. Las juntas están limpias previo a la aplicación. La boquilla presenta correcta adherencia y acabado uniforme.",
    puntosNoAceptables: "La boquilla se aplica antes de 48 horas. El adhesivo no ha terminado de secar al momento de aplicar. Existen movimientos en las piezas al momento de la aplicación. Las juntas presentan polvo o suciedad previa a la aplicación. La boquilla no logra adherencia adecuada.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-PI-05.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-IM-01",
    concepto: "Superficie preparada antes de impermeabilización",
    criterioAceptacion: "La superficie deberá encontrarse limpia, seca y libre de polvo antes de aplicar sistema impermeabilizante.",
    formaVerificacion: "Inspección visual previa a la aplicación. Confirmar retiro de residuos y corrección de fisuras previas.",
    puntosAceptables: "La superficie está limpia y seca. No existen fisuras sin tratar. Está lista para aplicación.",
    puntosNoAceptables: "Existen residuos o humedad excesiva. No se corrigieron fisuras previas. Se aplica sobre superficie sucia.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-IM-01.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-IM-02",
    concepto: "Traslapes y sellos correctamente ejecutados en impermeabilización",
    criterioAceptacion: "La impermeabilización deberá ejecutarse mediante sistema demalla de refuerzo con aplicación de impermeabilizante líquido, garantizando continuidad,adherencia y sellado adecuado en toda la superficie. Se deberá cumplir con lo siguiente: ● Lamalla de refuerzo deberá colocarse continua, sininterrupciones. ● Lostraslapes entre paños de malla deberán ser uniformesy suficientespara garantizar la continuidad del sistema. ● El impermeabilizante líquido deberá aplicarsecubriendocompletamente la malla, sin dejar zonas expuestas. ● Se deberá asegurar correctosellado en juntas, cambiosde dirección, esquinas y encuentros con elementos verticales.",
    formaVerificacion: "Inspección visual de continuidad en la malla. Verificar traslapes adecuados entre paños. Confirmar cobertura total del sistema líquido sobre la malla. Revisar sellos en puntos críticos (juntas, esquinas, bajantes, pretiles).",
    puntosAceptables: "La malla es continua en toda la superficie. Los traslapes son uniformes y garantizan continuidad del sistema. La malla se encuentra completamente. cubierta por el impermeabilizante. Los puntos críticos están correctamente sellados. El sistema presenta acabado uniforme y continuo.",
    puntosNoAceptables: "La malla presenta discontinuidades o cortes sin tratamiento. Los traslapes son insuficientes o inexistentes. Existen zonas donde la malla queda expuesta. Se observan áreas sin sellado en puntos críticos. La aplicación del impermeabilizante es irregular o incompleta.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-IM-02.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-CA-01",
    concepto: "Marcos de cancelería alineados antes de fijación definitiva",
    criterioAceptacion: "Los marcos deberán instalarse respetando alineación, nivel y escuadra antes de fijación final.",
    formaVerificacion: "Comprobar alineación y ajuste dentro del vano antes de sellar o fijar definitivamente.",
    puntosAceptables: "El marco está alineado. Se respeta nivel y escuadra. La fijación es correcta.",
    puntosNoAceptables: "Existe desalineación visible. El marco no respeta escuadra. Se fija sin verificación previa.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-CA-01.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-CA-02",
    concepto: "Preinstalaciones verificadas antes de cerrar muros",
    criterioAceptacion: "Todas las preinstalaciones hidráulicas y eléctricas deberán revisarse antes de cubrirse con aplanados o concreto.",
    formaVerificacion: "Confirmar ubicación y fijación conforme a planos antes del cierre.",
    puntosAceptables: "Coinciden con proyecto. Están correctamente fijadas. Fueron verificadas antes del cierre.",
    puntosNoAceptables: "Faltan elementos proyectados. Existen desplazamientos. No se realizó revisión previa.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-CA-02.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-CA-03",
    concepto: "Vano y elementos de cancelería conforme a especificación técnica",
    criterioAceptacion: "Los vanos destinados a cancelería deberán cumplir con tolerancias dimensionales controladas, y los elementos instalados deberán incluir componentes necesarios para evitar filtraciones. Se deberá cumplir con lo siguiente: ● Tolerancia máxima de descuadre en vano:1 cm ● Los canceles deberán incluirsardinel con altura mínimade 2.5 cm ● Estas condiciones son obligatorias para garantizar el correcto funcionamiento del sistema y evitar filtraciones de agua.",
    formaVerificacion: "Medir escuadra y dimensiones del vano previo a instalación. Confirmar que el descuadre no exceda 1 cm. Verificar la existencia y dimensión del sardinel. Inspeccionar correcta integración del sistema antes de cierre o sellado final.",
    puntosAceptables: "El vano cumple con la tolerancia máxima de 1. cm. El sardinel está presente y cumple con altura mínima de 2.5 cm. El sistema permite correcta instalación del cancel. No existen condiciones que comprometan la estanqueidad.",
    puntosNoAceptables: "El vano presenta descuadre mayor a 1 cm. No existe sardinel o su altura es menor a 2.5 cm. El vano no permite correcta instalación del cancel. Se detectan condiciones que favorezcan. filtraciones.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-CA-03.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-GE-01",
    concepto: "Limpieza del área previa a cada partida",
    criterioAceptacion: "Cada partida deberá ejecutarse sobre área limpia y libre de residuos que comprometan calidad del trabajo siguiente.",
    formaVerificacion: "Inspección visual previa al inicio de cada actividad.",
    puntosAceptables: "El área está limpia. No hay interferencias. La superficie está preparada.",
    puntosNoAceptables: "Existen residuos que afecten la ejecución. No se retiró material sobrante. Se inicia trabajo sobre superficie contaminada.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-GE-01.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "AC-GE-02",
    concepto: "Evidencia fotográfica y registro documental realizado",
    criterioAceptacion: "Cada etapa deberá documentarse mediante registro fotográfico y anotación en checklist antes de cerrar partida.",
    formaVerificacion: "Confirmar existencia de evidencia y registro correspondiente.",
    puntosAceptables: "Existe registro completo. Se documentó antes de continuar y la partida quedó formalmente liberada.",
    puntosNoAceptables: "No existe registro. No se documentó la verificación. La partida se cerró sin evidencia.",
    checklistType: "aseguramiento",
    imagenCorrecto: "/quality-base/TR-AC-M01/AC-GE-02.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
];

export const entregaManualSpecs = [
  {
    clave: "CC-FA-01",
    concepto: "Fachada limpia, uniforme y sin fisuras visibles",
    criterioAceptacion: "La fachada debe presentar un acabado homogéneo, sin residuos de obra, sin manchas visibles y sin fisuras o grietas perceptibles a simple vista.",
    formaVerificacion: "La inspección deberá realizarse desde el frente de la vivienda, recorriendo visualmente la superficie a una distancia aproximada de 1 a 2 metros, poniendo especial atención en esquinas, encuentros de materiales, marcos de puertas y ventanas.",
    puntosAceptables: "La superficie es uniforme en color y textura. No presenta fisuras visibles. No existen manchas ni residuos de obra. Los encuentros entre materiales se ven definidos y limpios.",
    puntosNoAceptables: "Existen fisuras visibles, aunque sean finas. Se observan manchas, escurrimientos o residuos de pintura. Se identifican parches o diferencias de tono entre secciones. Hay desprendimientos o irregularidades en la superficie.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-FA-01.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-FA-02",
    concepto: "La pintura exterior presenta acabado homogéneo y sin manchas",
    criterioAceptacion: "La pintura exterior deberá presentar un acabado uniforme en color y textura, sin variaciones perceptibles, escurrimientos, burbujas, descascaramientos ni manchas visibles bajo condiciones normales de iluminación.",
    formaVerificacion: "La inspección deberá realizarse recorriendo visualmente la fachada a una distancia de 1 metro, observando la superficie. Se deberá prestar especial atención a encuentros entre paños, esquinas, zonas cercanas a marcos de puertas y ventanas, y cambios de plano.",
    puntosAceptables: "Tono y brillo uniformes en todo el paño. Superficie continua sin escurrimientos ni acumulaciones Sin burbujas, descascaramientos ni marcas de. herramientas. Sin fisuras ni manchas visibles. Zonas de repinte indistinguibles del resto. Encuentros con marcos, plafón y zoclo limpios y bien definidos.",
    puntosNoAceptables: "Diferencia de tono perceptible entre paños. Escurrimientos, salpicaduras o acumulaciones visibles Burbujas, peladuras o descascaramientos. Marcas de rodillo o brocha visibles. Fisuras visibles aunque sean finas. Manchas de cualquier origen sin corregir. Zonas parchadas con tono diferente al paño.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-FA-02.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-FA-03",
    concepto: "La puerta principal abre y cierra correctamente, sin rozamientos",
    criterioAceptacion: "La puerta principal deberá operar de manera fluida, sin presentar resistencia excesiva, fricción contra el marco, desalineaciones o movimientos indebidos. El conjunto deberá encontrarse correctamente instalado y ajustado.",
    formaVerificacion: "Abrir y cerrar la puerta completamente al menos dos veces. Verificar que el movimiento sea continuo y uniforme. Observar el espacio entre hoja y marco, así como el funcionamiento del cerrojo y bisagras.",
    puntosAceptables: "La apertura y cierre son suaves y continuos. La hoja mantiene alineación uniforme con el marco. No existe fricción ni contacto indebido. El sistema de cierre funciona correctamente.",
    puntosNoAceptables: "La puerta roza contra el piso o el marco. Se requiere aplicar fuerza excesiva para abrir o cerrar. Se perciben desalineaciones visibles. Existen holguras o movimientos laterales indebidos. Se escuchan ruidos anormales en bisagras o cerradura.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-FA-03.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-FA-04",
    concepto: "Las cerraduras y herrajes de acceso funcionan correctamente",
    criterioAceptacion: "Las cerraduras, manijas, chapas y demás herrajes de la puerta principal deberán encontrarse correctamente instalados, firmes y en pleno funcionamiento, sin holguras, fallas mecánicas ni defectos visibles.",
    formaVerificacion: "Accionar la cerradura utilizando la llave correspondiente. Verificar apertura y cierre completos. Revisar que la manija y el conjunto no presenten movimiento indebido. Confirmar que el pestillo entre correctamente en el marco.",
    puntosAceptables: "La llave gira sin resistencia indebida. El sistema de cierre funciona de manera precisa. Los herrajes están firmes y correctamente alineados. No existen defectos visibles en el acabado.",
    puntosNoAceptables: "La llave no gira con normalidad. El pestillo no entra completamente en la contra. Existen movimientos o juego excesivo en la manija. Se perciben ruidos anormales al accionar el. mecanismo. Hay tornillos flojos o herrajes desalineados.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-FA-04.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-FA-05",
    concepto: "Las luminarias exteriores se encuentran funcionales y correctamente instaladas",
    criterioAceptacion: "Las luminarias exteriores deberán estar correctamente instaladas, firmemente sujetas y en pleno funcionamiento, sin presentar fallas eléctricas, movimientos indebidos o defectos visibles en su acabado.",
    formaVerificacion: "Accionar el interruptor correspondiente o energizar el circuito. Confirmar que la luminaria enciende correctamente. Revisar que el cuerpo esté firme, alineado y que no existan cables expuestos ni separaciones visibles contra el muro o plafón.",
    puntosAceptables: "Enciende de manera inmediata y estable. Está correctamente fijada y alineada. No presenta defectos visibles. La instalación eléctrica se encuentra protegida y oculta.",
    puntosNoAceptables: "La luminaria no enciende. Presenta parpadeo intermitente. Se encuentra suelta o desalineada. Existen cables visibles o mal protegidos. Se observan daños en la carcasa o en el cristal.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-FA-05.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-PE-01",
    concepto: "El piso exterior se encuentra nivelado y sin piezas sueltas",
    criterioAceptacion: "El piso exterior deberá encontrarse correctamente instalado, con superficie uniforme, sin desniveles perceptibles, piezas sueltas, fracturas ni desprendimientos.",
    formaVerificacion: "Recorrer el área pisando distintos puntos del piso para comprobar estabilidad. Observar visualmente la alineación de las piezas y verificar que no existan diferencias evidentes de nivel entre ellas.",
    puntosAceptables: "Las piezas se encuentran firmemente adheridas. La superficie es uniforme y estable. No existen daños visibles. La pendiente permite el correcto desalojo del agua.",
    puntosNoAceptables: "Se perciben piezas sueltas o movimiento al pisar. Existen desniveles notorios entre losetas. Se observan fracturas, esquinas rotas o desprendimientos. Hay hundimientos o acumulaciones de agua por falta de pendiente.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-PE-01.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-PE-02",
    concepto: "Los muros perimetrales no presentan grietas visibles",
    criterioAceptacion: "Los muros perimetrales deberán presentar superficies íntegras, sin fisuras, grietas, desprendimientos o irregularidades visibles que afecten su apariencia o desempeño.",
    formaVerificacion: "Realizar inspección visual recorriendo la totalidad del muro, observando especialmente esquinas, juntas, cambios de material y zonas cercanas a castillos o dalas. La revisión deberá efectuarse a una distancia aproximada de 1 a 2 metros.",
    puntosAceptables: "La superficie del muro es continua y uniforme. No se aprecian grietas ni fisuras visibles. No existen desprendimientos o irregularidades.",
    puntosNoAceptables: "Existen grietas verticales, horizontales o diagonales visibles. Se observan microfisuras en esquinas o encuentros. Hay desprendimientos de recubrimiento. Se presentan separaciones entre elementos constructivos.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-PE-02.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-PE-03",
    concepto: "Las salidas de agua exteriores funcionan correctamente",
    criterioAceptacion: "Las salidas de agua exteriores deberán encontrarse firmemente instaladas, operar correctamente y no presentar fugas durante su uso.",
    formaVerificacion: "Abrir completamente la llave y comprobar flujo continuo de agua. Cerrar la llave y verificar que no exista goteo posterior. Revisar visualmente la unión contra el muro.",
    puntosAceptables: "El flujo de agua es continuo y estable. No existen fugas. La llave se encuentra firme y correctamente instalada.",
    puntosNoAceptables: "No existe flujo de agua. Se presentan fugas en la base o conexiones. La llave se encuentra floja o con movimiento indebido. Se observa goteo continuo después del cierre.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-PE-03.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-PE-04",
    concepto: "Los registros y drenajes se encuentran libres de obstrucción",
    criterioAceptacion: "Los registros y drenajes exteriores deberán encontrarse despejados, correctamente instalados y permitir el adecuado desalojo del agua.",
    formaVerificacion: "Inspeccionar visualmente el interior del registro. Verificar que no existan residuos de obra. Comprobar que las tapas estén firmes y alineadas.",
    puntosAceptables: "El interior se encuentra limpio. La tapa está firme y alineada. El sistema permite el correcto desalojo del agua.",
    puntosNoAceptables: "Existen residuos sólidos o acumulación de material. La tapa se encuentra suelta o desalineada. Se observan obstrucciones que impidan el flujo. Hay acumulación visible de agua por falta de pendiente.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-PE-04.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-SC-01",
    concepto: "Los pisos interiores se encuentran alineados, nivelados y sin daños",
    criterioAceptacion: "Los pisos interiores deberán estar correctamente instalados, con alineación uniforme entre piezas, superficie nivelada y sin fracturas, desprendimientos o daños visibles.",
    formaVerificacion: "Recorrer el área caminando sobre distintas zonas del piso. Observar la alineación de juntas y comprobar que no existan diferencias perceptibles de nivel entre piezas.",
    puntosAceptables: "Las piezas están firmemente adheridas. Existen desniveles visibles entre losetas 1 < mm. No existen daños visibles. Las juntas mantienen alineación continua.",
    puntosNoAceptables: "Se perciben piezas sueltas o movimiento al pisar. Existen desniveles visibles entre losetas ≥ 1. mm. Hay piezas fracturadas, despostilladas o con esquinas dañadas. Se observan juntas irregulares o desalineadas.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-SC-01.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-SC-02",
    concepto: "Los muros interiores presentan acabado uniforme y sin imperfecciones visibles",
    criterioAceptacion: "Los muros interiores deberán presentar acabado homogéneo, sin manchas, fisuras, ondulaciones, burbujas o marcas visibles en condiciones normales de iluminación.",
    formaVerificacion: "Inspeccionar visualmente los muros recorriendo la estancia en sentido horizontal. Prestar atención a esquinas, encuentros con plafón y marcos de puertas o ventanas.",
    puntosAceptables: "El acabado es uniforme en color y textura. No existen fisuras ni manchas. La superficie se percibe continua y bien terminada.",
    puntosNoAceptables: "Se observan manchas, parches o diferencias de tono. Existen fisuras visibles. Hay irregularidades, burbujas o desprendimientos. Se identifican marcas de herramientas o lijado deficiente.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-SC-02.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-SC-03",
    concepto: "Las tapas e interruptores de luz se encuentran completamente funcionales y en buen estado estético",
    criterioAceptacion: "Las tapas e interruptores deberán operar correctamente y presentar acabado limpio, alineado y sin defectos visibles.",
    formaVerificacion: "Accionar cada interruptor al menos una vez. Confirmar encendido y apagado correcto. Revisar visualmente la alineación y condición de la tapa.",
    puntosAceptables: "El interruptor opera con normalidad. La tapa está firme y alineada. No existen manchas ni daños visibles.",
    puntosNoAceptables: "El interruptor no acciona correctamente. Se percibe movimiento o está flojo. Existen manchas de pintura o rayones visibles. La tapa está desalineada o separada del muro.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-SC-03.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-SC-04",
    concepto: "Los contactos eléctricos se encuentran firmemente instalados y funcionales",
    criterioAceptacion: "Los contactos eléctricos deberán encontrarse correctamente fijados al muro, alineados y en pleno funcionamiento, sin movimiento indebido ni defectos visibles.",
    formaVerificacion: "Conectar un dispositivo eléctrico portátil para comprobar suministro de energía. Verificar que el contacto no presente movimiento al introducir o retirar la clavija. Revisar visualmente alineación y estado de la tapa.",
    puntosAceptables: "Suministra energía correctamente. Se encuentra firme y alineado. No presenta daños ni defectos visibles.",
    puntosNoAceptables: "No existe suministro eléctrico. El contacto presenta movimiento o se hunde al presionarlo. La tapa está desalineada o separada del muro. Existen fisuras, manchas o daños visibles.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-SC-04.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-SC-05",
    concepto: "Las ventanas abren y cierran correctamente, sin holguras",
    criterioAceptacion: "Las ventanas deberán operar de manera fluida, sin resistencia indebida, holguras excesivas ni desalineaciones. Los sistemas de cierre deberán funcionar correctamente.",
    formaVerificacion: "Abrir y cerrar cada ventana completamente. Verificar suavidad del desplazamiento y correcto funcionamiento del seguro. Revisar visualmente alineación y ajuste al marco.",
    puntosAceptables: "La apertura y cierre son suaves y uniformes. El sistema de cierre funciona correctamente. No existen holguras ni desalineaciones.",
    puntosNoAceptables: "Existe dificultad para abrir o cerrar. Se perciben holguras o movimiento lateral excesivo. El seguro no funciona correctamente. Hay desalineación visible entre hoja y marco.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-SC-05.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-SC-06",
    concepto: "Los sellos perimetrales en cancelería se encuentran completos y uniformes",
    criterioAceptacion: "Los sellos de silicón o material equivalente deberán encontrarse continuos, bien adheridos y sin interrupciones visibles en el perímetro de la cancelería.",
    formaVerificacion: "Inspeccionar visualmente el contorno completo de ventanas y elementos de cancelería. Confirmar que el sellado sea uniforme y continuo.",
    puntosAceptables: "El sellado es continuo y uniforme. No existen espacios sin cubrir. El acabado es limpio y consistente.",
    puntosNoAceptables: "Existen tramos sin sellar. Se observan discontinuidades o desprendimientos. El sellado presenta exceso irregular o acabado deficiente. Se identifican separaciones entre marco y. muro.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-SC-06.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-CN-01",
    concepto: "La tarja no presenta filtraciones ni movimiento",
    criterioAceptacion: "La tarja deberá encontrarse correctamente instalada, firmemente fijada y sin presentar filtraciones en conexiones o uniones.",
    formaVerificacion: "Abrir la llave y permitir el flujo de agua durante algunos segundos. Revisar visualmente la parte inferior para detectar posibles fugas. Comprobar que la tarja no presente movimiento al ejercer ligera presión.",
    puntosAceptables: "No existen fugas durante ni después del uso. La tarja se encuentra firme. El sellado es continuo y uniforme.",
    puntosNoAceptables: "Existen fugas en conexiones o sifón. Se observa humedad bajo la tarja. La tarja presenta movimiento o separación. del mueble. El sellado perimetral está incompleto o desprendido.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-CN-01.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-CN-02",
    concepto: "La mezcladora funciona correctamente y sin fugas",
    criterioAceptacion: "La mezcladora deberá operar suavemente, permitir regulación adecuada de temperatura y no presentar fugas en cuerpo o conexiones.",
    formaVerificacion: "Accionar agua fría y caliente. Confirmar flujo continuo y correcto cierre. Revisar visualmente la base y conexiones.",
    puntosAceptables: "El flujo es estable. No existen fugas. El accionamiento es suave y firme.",
    puntosNoAceptables: "Existen fugas en base o conexiones. El cierre no detiene completamente el flujo. El movimiento es rígido o presenta juego excesivo. Se escuchan ruidos anormales.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-CN-02.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-CN-03",
    concepto: "Los muebles de cocina se encuentran alineados y firmemente instalados",
    criterioAceptacion: "Los muebles deberán estar correctamente alineados, nivelados y firmemente anclados, sin movimientos indebidos ni defectos visibles.",
    formaVerificacion: "Abrir y cerrar puertas y cajones. Revisar alineación horizontal y vertical. Comprobar firmeza al ejercer presión ligera.",
    puntosAceptables: "La alineación es uniforme. Los muebles están firmemente fijados. No existen daños ni defectos visibles.",
    puntosNoAceptables: "Existen desalineaciones visibles entre puertas. Los módulos presentan movimiento. Se observan desprendimientos o daños. Las uniones presentan separación visible.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-CN-03.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-CN-04",
    concepto: "Las puertas y cajones abren y cierran correctamente",
    criterioAceptacion: "Las puertas y cajones deberán operar suavemente, sin fricción indebida ni desalineaciones.",
    formaVerificacion: "Abrir y cerrar cada elemento completamente. Verificar suavidad del recorrido y correcto ajuste al cerrar.",
    puntosAceptables: "El movimiento es suave y continuo. El cierre es completo y uniforme. No existen desajustes visibles.",
    puntosNoAceptables: "Existe rozamiento o fricción. No cierran completamente. Presentan desalineación. Se perciben ruidos anormales en herrajes.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-CN-04.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-CN-05",
    concepto: "Los sellos de silicón se encuentran completos y bien aplicados",
    criterioAceptacion: "Los sellos de silicón deberán ser continuos, uniformes y correctamente adheridos en encuentros entre superficies.",
    formaVerificacion: "Inspeccionar visualmente las uniones entre muro, cubierta y tarja. Confirmar continuidad y acabado limpio.",
    puntosAceptables: "El sellado es continuo y uniforme. No existen espacios sin cubrir. El acabado es limpio y consistente.",
    puntosNoAceptables: "Existen tramos sin sellar. El sellado presenta interrupciones o desprendimientos. Se observa exceso irregular o acabado deficiente. Hay separación visible entre superficies.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-CN-05.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-RE-01",
    concepto: "Las puertas interiores abren y cierran sin rozamiento",
    criterioAceptacion: "Las puertas interiores deberán operar de manera fluida, sin fricción contra marco o piso, y mantener correcta alineación en posición cerrada.",
    formaVerificacion: "Abrir y cerrar completamente cada puerta. Observar el espacio entre hoja y marco. Confirmar que no exista contacto indebido durante el recorrido.",
    puntosAceptables: "El movimiento es suave y continuo. No existe fricción ni contacto indebido. La alineación es uniforme.",
    puntosNoAceptables: "La puerta roza contra el marco o el piso. Se requiere fuerza excesiva para accionar. Existe desalineación visible. La puerta no cierra correctamente.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-RE-01.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-RE-02",
    concepto: "Las cerraduras funcionan correctamente",
    criterioAceptacion: "Las cerraduras interiores deberán operar correctamente, permitiendo apertura y cierre sin dificultad ni fallas mecánicas.",
    formaVerificacion: "Accionar el mecanismo de cierre varias veces. Confirmar correcto funcionamiento del pestillo y ajuste al marco.",
    puntosAceptables: "El cierre es preciso y firme. El accionamiento es suave. No existen fallas visibles.",
    puntosNoAceptables: "El mecanismo no acciona correctamente. El pestillo no entra completamente en la. contra. Se requiere fuerza excesiva. Existe movimiento indebido en la manija.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-RE-02.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-RE-03",
    concepto: "Los closets se encuentran firmemente instalados y alineados",
    criterioAceptacion: "Los closets deberán estar correctamente fijados, alineados y sin movimientos indebidos. Las puertas y componentes deberán operar adecuadamente.",
    formaVerificacion: "Abrir y cerrar puertas o cajones. Revisar alineación vertical y horizontal. Confirmar firmeza al ejercer presión ligera.",
    puntosAceptables: "La instalación es firme. La alineación es uniforme. No existen defectos visibles.",
    puntosNoAceptables: "Se observan desalineaciones visibles. Existen movimientos o inestabilidad. Hay separaciones entre módulos. Se identifican daños en acabado.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-RE-03.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-RE-04",
    concepto: "Las ventanas presentan correcto funcionamiento y sellado",
    criterioAceptacion: "Las ventanas deberán operar sin dificultad y contar con sellado perimetral continuo que garantice ajuste adecuado.",
    formaVerificacion: "Abrir y cerrar completamente. Verificar funcionamiento del sistema de cierre. Inspeccionar visualmente el sellado perimetral.",
    puntosAceptables: "El movimiento es suave y uniforme. El cierre es firme. El sellado es continuo y uniforme.",
    puntosNoAceptables: "Existe dificultad en el movimiento. El seguro no funciona correctamente. Se observan espacios sin sellar. Hay desalineaciones visibles.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-RE-04.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-BA-01",
    concepto: "El WC se encuentra firmemente anclado y sin movimiento",
    criterioAceptacion: "El WC deberá estar correctamente fijado al piso, sin presentar movimiento lateral o vertical, y operar adecuadamente sin fugas visibles.",
    formaVerificacion: "Ejercer ligera presión lateral sobre el sanitario para comprobar estabilidad. Accionar la descarga y observar correcto funcionamiento. Revisar visualmente la base y conexiones.",
    puntosAceptables: "El sanitario se encuentra firme y estable. No existen fugas visibles. El sistema de descarga opera correctamente. La tubería cuenta con respiradero.",
    puntosNoAceptables: "El WC presenta movimiento al ejercer presión. Existen fugas en la base o conexiones. La descarga no funciona correctamente. Se observan separaciones entre base y piso.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-BA-01.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-BA-02",
    concepto: "El lavabo no presenta filtraciones ni fisuras",
    criterioAceptacion: "El lavabo deberá encontrarse íntegro, sin fisuras en la superficie, correctamente instalado y sin fugas en conexiones.",
    formaVerificacion: "Abrir la llave y permitir flujo de agua. Revisar la parte inferior y conexiones para detectar posibles fugas. Inspeccionar visualmente la superficie del lavabo.",
    puntosAceptables: "No existen fisuras ni fugas. El lavabo se encuentra firme. El sellado es continuo y uniforme.",
    puntosNoAceptables: "Existen fisuras visibles en la pieza. Se presentan fugas en conexiones. El lavabo tiene movimiento indebido. Se observan separaciones en el sellado.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-BA-02.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-BA-03",
    concepto: "La regadera funciona correctamente y con presión adecuada",
    criterioAceptacion: "La regadera deberá suministrar agua de manera continua y uniforme, sin fugas en conexiones ni fallas en el control de temperatura.",
    formaVerificacion: "Abrir el suministro de agua. Confirmar flujo constante y adecuado. Verificar que el cierre detenga completamente el flujo.",
    puntosAceptables: "El flujo es continuo y uniforme. No existen fugas. El control opera correctamente.",
    puntosNoAceptables: "El flujo es irregular o insuficiente. Existen fugas en conexiones. El control no regula correctamente temperatura o cierre. Se observa goteo posterior al cierre.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-BA-03.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-BA-04",
    concepto: "Los sellos de silicón en regadera y lavabo se encuentran completos y uniformes",
    criterioAceptacion: "Los sellos deberán ser continuos, sin interrupciones ni desprendimientos, garantizando correcta unión entre superficies.",
    formaVerificacion: "Inspeccionar visualmente los encuentros entre muro, piso y piezas sanitarias. Confirmar continuidad y acabado limpio.",
    puntosAceptables: "El sellado es continuo y uniforme. No existen espacios sin cubrir. El acabado es limpio y consistente.",
    puntosNoAceptables: "Existen tramos sin sellar. Se observan desprendimientos o. discontinuidades. El acabado es irregular o excesivo. Hay separación visible entre superficies.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-BA-04.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-BA-05",
    concepto: "Los accesorios (toalleros, porta papel, etc.) se encuentran firmemente instalados",
    criterioAceptacion: "Los accesorios deberán estar correctamente fijados al muro, alineados y sin movimiento indebido.",
    formaVerificacion: "Ejercer ligera presión sobre cada accesorio. Confirmar firmeza y correcta alineación.",
    puntosAceptables: "Se encuentra firme y correctamente alineado. No presenta defectos visibles. La fijación es segura y estable.",
    puntosNoAceptables: "El accesorio presenta movimiento o inestabilidad. Existen tornillos visibles sueltos. Se observan daños en el acabado. Está desalineado respecto al eje horizontal.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-BA-05.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-BA-06",
    concepto: "Señalización de uso en sanitario colocada correctamente",
    criterioAceptacion: "El área de baño deberá contar con un letrero permanente, visible y correctamente instalado con la leyenda: “Prohibido tirar papel en el inodoro”. El letrero deberá encontrarse en una ubicación estratégica que permita su fácil lectura por parte del usuario.",
    formaVerificacion: "Inspección visual dentro del baño. Confirmar la presencia del letrero con la leyenda indicada. Verificar que se encuentre firmemente fijado y en buen estado. Validar que su ubicación sea visible para el usuario.",
    puntosAceptables: "El letrero está presente en el baño. Contiene la leyenda correcta. Se encuentra firmemente instalado y en buen estado. Es claramente visible para el usuario.",
    puntosNoAceptables: "No existe señalización en el baño. El letrero no contiene la leyenda correcta. Se encuentra desprendido, dañado o mal instalado. No es visible o está colocado en una. ubicación inadecuada.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-BA-06.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-PI-01",
    concepto: "Sistema de drenaje de piscina verificado previo a entrega",
    criterioAceptacion: "La piscina deberá contar con una verificación previa de su sistema de drenaje, asegurando el correcto funcionamiento del tapón de bronce y el desalojo adecuado del agua. La prueba deberá realizarse antes de la entrega de la vivienda.",
    formaVerificacion: "Llenar la piscina con agua. Accionar el sistema de drenaje. Verificar correcto funcionamiento del tapón de bronce. Confirmar que el agua se desaloja sin obstrucciones.",
    puntosAceptables: "El sistema de drenaje funciona. correctamente. El tapón de bronce opera adecuadamente. El desalojo de agua es continuo y sin obstrucciones. La prueba fue realizada previo a la entrega.",
    puntosNoAceptables: "El sistema de drenaje no funciona. El tapón de bronce presenta fallas o no sella correctamente. El desalojo de agua es lento o presenta obstrucciones. No se realizó prueba previa a la entrega.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-PI-01.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-PI-02",
    concepto: "Señalización de uso y mantenimiento en piscina colocada",
    criterioAceptacion: "La piscina deberá contar con un letrero informativo visible que indique recomendaciones básicas de uso y mantenimiento para el usuario. El letrero deberá encontrarse correctamente instalado, ser legible y estar ubicado en un punto visible.",
    formaVerificacion: "Inspección visual del área de piscina. Confirmar presencia del letrero informativo. Verificar que se encuentre en buen estado y firmemente instalado. Validar que su ubicación sea visible para el usuario.",
    puntosAceptables: "Existe señalización en la piscina. El contenido es claro y legible. Se encuentra correctamente instalado. Es visible para el usuario.",
    puntosNoAceptables: "No existe señalización en la piscina. El letrero es ilegible, incorrecto o incompleto. Se encuentra dañado o desprendido. No es visible para el usuario.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-PI-02.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-AZ-01",
    concepto: "La impermeabilización se encuentra uniforme y sin desprendimientos visibles",
    criterioAceptacion: "La superficie impermeabilizada deberá presentar aplicación uniforme, sin zonas descubiertas, burbujas, fisuras, desprendimientos o acumulaciones irregulares de material.",
    formaVerificacion: "Realizar inspección visual completa de la azotea, revisando especialmente encuentros con muros, bajantes y pretiles. Confirmar continuidad del recubrimiento.",
    puntosAceptables: "La aplicación es continua y uniforme. No existen zonas descubiertas. La superficie se encuentra íntegra y sin. defectos visibles.",
    puntosNoAceptables: "Existen zonas sin recubrimiento. Se observan burbujas, fisuras o desprendimientos. Hay acumulaciones irregulares o aplicación discontinua. Se identifican grietas visibles en la superficie.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-AZ-01.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-AZ-02",
    concepto: "El tinaco se encuentra correctamente instalado y sin fugas",
    criterioAceptacion: "El tinaco deberá estar firmemente instalado, correctamente nivelado y sin presentar fugas en conexiones o en su estructura.",
    formaVerificacion: "Inspeccionar visualmente la base de apoyo y conexiones hidráulicas. Confirmar que no existan filtraciones visibles y que la instalación esté firme.",
    puntosAceptables: "La instalación es firme y nivelada. No existen fugas visibles. Las conexiones se encuentran correctamente selladas.",
    puntosNoAceptables: "Se observan fugas en conexiones. El tinaco presenta inclinación evidente. La base de apoyo es inestable. Existen daños visibles en el cuerpo del depósito.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-AZ-02.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-AZ-03",
    concepto: "Los bajantes pluviales se encuentran firmemente sujetos y libres de obstrucción",
    criterioAceptacion: "Los bajantes deberán estar correctamente fijados a la estructura, alineados y sin obstrucciones que impidan el adecuado desalojo del agua pluvial.",
    formaVerificacion: "Inspeccionar visualmente la sujeción a muros y revisar que no existan deformaciones o acumulación de residuos visibles en el interior.",
    puntosAceptables: "El bajante está firmemente sujeto. No presenta deformaciones. Se encuentra libre de obstrucciones visibles. Las uniones están correctamente ajustadas.",
    puntosNoAceptables: "Existen sujeciones flojas o desprendidas. Se observan deformaciones en el tubo. Hay obstrucciones visibles. Existen separaciones en uniones o conexiones.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-AZ-03.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
  {
    clave: "CC-SÑ-01",
    concepto: "Señalización técnica en instalaciones colocada correctamente",
    criterioAceptacion: "Las instalaciones de la vivienda deberán contar con señalización técnica visible en puntos clave, indicando: ● Presión máxima de operación (PSI) en instalaciones hidráulicas. ● Voltaje máximo en instalaciones eléctricas. ● Recomendaciones básicas para intervención futura por terceros. La señalización deberá encontrarse correctamente instalada, ser legible y estar ubicada en zonas estratégicas que faciliten su consulta durante mantenimiento o modificaciones.",
    formaVerificacion: "Inspección visual en áreas de instalaciones (centro de carga, equipos hidráulicos, azotea, cuartos de servicio, etc.). Confirmar presencia de señalización con información clara y legible. Verificar correcta fijación y estado del letrero. Validar que la ubicación sea accesible y visible para el usuario o proveedor externo.",
    puntosAceptables: "Existe señalización en los puntos clave de instalaciones. La información es clara, completa y legible. Los letreros se encuentran firmemente instalados y en buen estado. La ubicación permite su fácil identificación. durante intervención o mantenimiento.",
    puntosNoAceptables: "No existe señalización en instalaciones. La información es incompleta, incorrecta o ilegible. Los letreros se encuentran dañados, desprendidos o mal instalados. La señalización no es visible o está ubicada en. zonas no accesibles.",
    checklistType: "entrega",
    imagenCorrecto: "/quality-base/TR-CC-M01/CC-SÑ-01.jpg",
    evidenceRequired: 1,
    clasificacion: "menor",
    peso: 1,
  },
];
